---
title: "DC Figure 2"
output: rmarkdown::github_document
---

## Set up

Load R libraries
```{r message = F, results = F, warning = F, load_r_libraries}
library(ggplot2)

library(reticulate)
use_python("/projects/home/tlchan/.conda/envs/myenv/bin/python")
```

Load python libraries
```{python load_python_packages}
import matplotlib.pyplot as plt
import pandas as pd
import pegasus as pg
import seaborn as sns

import sys
sys.path.append("/projects/home/tlchan/github_code/ascites/functions")
import python_functions
```

## Figure 1C
```{python results = 'hold', fig_1C}
dc_cluster_palette = {
    "cDC2": "#FF0029",
    "pDC": "#377EB8",
    "cDC1": "#66A61E",
    "PIGR+DC": "#984EA3",
    "mREGDC": "#00D2D5",
    "ASDC": "#FF7F00",
}

# Load single-cell object
pigr_dc_data = pg.read_input(
    '/projects/home/tlchan/projects/ascites/dc_hunting/clusterings/pigr_dc_project_R2_300mg_20pm_scVI_multi_res/1.3/data/pseudobulk/pigr_dc_project_R2_300mg_20pm_scVI_1_3_complete_with_pb.zarr.zip')

python_functions.plot_umap(lin_data=pigr_dc_data,
                           color="annots",
                           palette=dc_cluster_palette)
```

## Figure 1D
```{python results = 'hold', fig_1D}
channel_palette = {
    "Original channels": "#808080",
    "PIGR_1029_GEX": "#E69F00",
    "cDCs_1029_GEX": "#00008B"
}

# Load single-cell object
pigr_dc_data = pg.read_input(
    '/projects/home/tlchan/projects/ascites/dc_hunting/clusterings/pigr_dc_project_R2_300mg_20pm_scVI_multi_res/1.3/data/pseudobulk/pigr_dc_project_R2_300mg_20pm_scVI_1_3_complete_with_pb.zarr.zip')

# Relabel obs for function
pigr_dc_data.obs['Channel'] = pigr_dc_data.obs['Channel'].cat.add_categories("Original channels")
pigr_dc_data.obs.loc[~pigr_dc_data.obs['Channel'].isin(["PIGR_1029_GEX", "cDCs_1029_GEX"]), "Channel"] = "Original channels"
pigr_dc_data.obs['Channel'] = pigr_dc_data.obs['Channel'].cat.remove_unused_categories().astype(str)

pigr_dc_data.obs.loc[pigr_dc_data.obs["Channel"] == 'Original channels', 'size'] = 1
pigr_dc_data.obs.loc[pigr_dc_data.obs["Channel"] != 'Original channels', 'size'] = 6

python_functions.plot_umap(lin_data=pigr_dc_data,
                           color="Channel",
                           palette=channel_palette,
                           size=list(pigr_dc_data.obs['size']))
```

## Figure 1E
```{python results = 'hold', fig_1E}
pigr_dc_data = pg.read_input(
    '/projects/home/tlchan/projects/ascites/dc_hunting/clusterings/pigr_dc_project_R1_300mg_20pm_scVI_multi_res/1.3/data/pseudobulk/pigr_dc_project_R1_300mg_20pm_scVI_1_3_complete_with_pb.zarr.zip')

python_functions.plot_feature(lin_data=pigr_dc_data,
                              genes=['CD1C', 'CLEC9A', 'PRDM16', 'PIGR', 'SFTPD', 'RORC', ],
                              ncol=2,
                              nrow=3)
```

## Figure 1F
```{r message = F, results = F, warning = F, fig.width = 14, fig.height = 6, fig_1F}

pigr_dc_counts <- read.csv("/projects/home/tlchan/pigr_dc_counts.csv")
pigr_dc_counts$channel <- "PIGR"

ggplot(pigr_dc_counts, aes(x = channel, y = count, fill = annot)) +
    geom_bar(stat = 'identity', position = 'stack') +
    labs(fill = "Cluster") +
    xlab("Cluster") +
    ylab("Count") +
    ggtitle("PIGR+ DC channel by clusters") +
    theme_classic(base_size = 15) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

## Figure 1G
```{python results = 'hold', fig_1G}
corr_mat = pd.read_csv("/projects/home/tlchan/projects/ascites/dc_hunting/data/dc_pca_mean_matrix.csv")
corr_mat = corr_mat.corr()

cols = ['PIGR_1029_GEX', 'cDCs_1029_GEX']
rows = ['newDC: PRDM16, PIGR', 'mregDCs: LAMP3, CCR7', 'pDC: LILRA4, IL3RA', 'cDC1: CLEC9A, XCR1', 'cDC2: CD1C, CD33high',
        'cDC2: CD1C, CD33low', 'cDC3: CD1C, VCAN', 'cDC5: SIGLEC6, PPP1R14A', 'cDC: CD1C, FCGR3A', 'cDC: IL1R2, NR4A2']
corr_mat = corr_mat.loc[rows, cols]

fig, ax = plt.subplots(figsize=(8, 14))
sns.heatmap(corr_mat,
            cmap=sns.diverging_palette(220, 10, as_cmap=True),
            vmin=-0, vmax=1.0,
            square=True, ax=ax)
fig.tight_layout()
plt.show()
plt.close(fig)
```
