---
title: "Supplemental Figure 6"
output: rmarkdown::github_document
---

## Set up

Load R libraries
```{r message = F, results = F, warning = F, load_r_libraries}
library(ggpubr)
library(ggrepel)
library(glue)
library(tidyverse)

library(reticulate)
use_python("/projects/home/nealpsmith/software/pegasus_new_py/bin/python")

```

Load python libraries
```{python load_python_packages}
import math
import matplotlib.pyplot as plt
import os
import pandas as pd
import pegasus as pg
import scanpy as sc
from matplotlib.lines import Line2D
import matplotlib as mpl
import numpy as np

import matplotlib.colors as clr
mpl.rcParams['axes.spines.right'] = False
mpl.rcParams['axes.spines.top'] = False
mpl.rcParams['pdf.fonttype'] = 42

import sys
sys.path.append("../../functions")
import python_functions

```

## Supplemental Figure 6A
```{r message = F, results = F, warning = F, fig.width = 5.5, fig.height = 8, supp_7A}
# Load data
abundance <- read.csv("/projects/home/tlchan/projects/ascites/results/abundance/w_peritoneal/ascites_abundance.csv")

# Subset DCs
abundance <- abundance %>%
    filter(lineage == "dc")

# Get immune count
abundance <- abundance %>%
    group_by(patient_id, tissue_type, cluster, .drop = FALSE) %>%
    summarize(abundance = n())

# Account for patient/tissue pairs that contributed zero cells to clusters
combos <- expand.grid(unique(abundance$patient_id), unique(abundance$tissue_type), unique(abundance$cluster)) %>% `colnames<-`(c("patient_id", "tissue_type", "cluster"))

abundance <- combos %>%
    left_join(abundance, by = c("patient_id", "tissue_type", "cluster")) %>%
    replace(is.na(.), 0)

abundance <- abundance %>%
    group_by(patient_id, tissue_type) %>%
    filter(sum(abundance) > 50)

# Get statistics
abundance <- abundance %>%
    group_by(patient_id, tissue_type) %>%
    mutate(proportion = abundance / sum(abundance) * 100) %>%
    mutate(log_proportion = log1p(proportion)) %>%
    mutate(tissue_type = factor(tissue_type, levels = c("blood", "ascites")))

# Filter for ascites, and non-null values
abundance <- abundance %>%
    filter(tissue_type == 'ascites') %>%
    filter(!is.na(proportion)) %>%
    ungroup() %>%
    select(patient_id, cluster, log_proportion)

### DC NEW CORRELATION
c12_stats <- abundance %>%
    filter(cluster == 12) %>%
    rename("log_newDC_proportion" = log_proportion) %>%
    select(patient_id, log_newDC_proportion)

analyte_list <- c("IL-6", "IL-10")

# pdf("/projects/home/tlchan/fig_panels/supp_7a.pdf", width = 5.5, height = 8)
supp_df <- data.frame()
for (an in analyte_list) {
    sf_data <- read.csv("/projects/home/tlchan/projects/ascites/results/secreted_factors/integrated_data/secreted_factors_updated.csv", row.names = 1)
    sf_data <- sf_data[sf_data["diluted"] == "No",]
    sf_data <- sf_data[sf_data["analyte"] == an,]
    sf_data <- sf_data[sf_data["type"] == "ascites",]
    sf_data$log_concentration <- log(sf_data$concentration)

    sf_data <- sf_data %>%
        merge(c12_stats, by = "patient_id")
  supp_df <- rbind(supp_df, sf_data)

    p <- ggplot(sf_data, aes(x = log_concentration, y = log_newDC_proportion)) +
        geom_point(pch = 19, size = 4) +
        geom_smooth(method = "lm", formula = y ~ x) +
        stat_cor(method = "pearson", size = 7) +
        xlab("log(concentration)") +
        ylab("log(DC: PIGR, RORC percentage)") +
        ggtitle(glue("Ascites, {an}")) +
        theme_classic(base_size = 28)
    print(p)
}
# dev.off()
write.csv(supp_df, "/projects/home/nealpsmith/projects/ascites/data/plot_data/fig_s6a.csv", row.names = FALSE)

```

## Supplemental Figure 6B
```{r message = F, results = F, warning = F, fig.width = 5.5, fig.height = 8, supp_7B}
# Load data
abundance <- read.csv("/projects/home/tlchan/projects/ascites/results/abundance/w_peritoneal/ascites_abundance.csv")

# Subset DCs
abundance <- abundance %>%
    filter(lineage == "dc")

# Get immune count
abundance <- abundance %>%
    group_by(patient_id, tissue_type, cluster, .drop = FALSE) %>%
    summarize(abundance = n())

# Account for patient/tissue pairs that contributed zero cells to clusters
combos <- expand.grid(unique(abundance$patient_id), unique(abundance$tissue_type), unique(abundance$cluster)) %>% `colnames<-`(c("patient_id", "tissue_type", "cluster"))

abundance <- combos %>%
    left_join(abundance, by = c("patient_id", "tissue_type", "cluster")) %>%
    replace(is.na(.), 0)

abundance <- abundance %>%
    group_by(patient_id, tissue_type) %>%
    filter(sum(abundance) > 50)

# Get statistics
abundance <- abundance %>%
    group_by(patient_id, tissue_type) %>%
    mutate(proportion = abundance / sum(abundance) * 100) %>%
    mutate(log_proportion = log1p(proportion)) %>%
    mutate(tissue_type = factor(tissue_type, levels = c("blood", "ascites")))

# Filter for ascites, and non-null values
abundance <- abundance %>%
    filter(tissue_type == 'ascites') %>%
    filter(!is.na(proportion)) %>%
    ungroup() %>%
    select(patient_id, cluster, log_proportion)

### DC NEW CORRELATION
c12_stats <- abundance %>%
    filter(cluster == 12) %>%
    rename("log_newDC_proportion" = log_proportion) %>%
    select(patient_id, log_newDC_proportion)

else_stats <- abundance %>%
    filter(cluster != 12)

dc_stats <- merge(c12_stats, else_stats, by = "patient_id")

cluster_list <- c('1', '2', '9', '13')

# pdf("/projects/home/tlchan/fig_panels/supp_7b.pdf", width = 5.5, height = 8)
supp_df <- data.frame()

for (clust in cluster_list) {
    clust_data <- dc_stats %>%
        filter(cluster == clust)
  supp_df <- rbind(supp_df, clust_data)

    p <- ggplot(clust_data, aes(x = log_proportion, y = log_newDC_proportion)) +
        geom_point(pch = 19, size = 4) +
        geom_smooth(method = "lm", formula = y ~ x) +
        stat_cor(method = "pearson", size = 7) +
        xlab("log(patient percentage)") +
        ylab("log(DC: PIGR, RORC percentage)") +
        ggtitle(glue("Ascites, Cluster {clust}")) +
        theme_classic(base_size = 28)
    print(p)
}
# dev.off()
# paper_ids <- read.csv("/projects/home/nealpsmith/projects/ascites/data/patient_paper_ids.csv")
# supp_df %>%
#     rename("log_DC_RORC_proportion" = "log_newDC_proportion") %>%
#     left_join(paper_ids, by = "patient_id") %>%
#     dplyr::select(-patient_id) %>%
#     write.csv("/projects/home/nealpsmith/projects/ascites/data/plot_data/fig_s6b.csv", row.names = FALSE)


```

## Supplemental Figure 6F
```{python results = 'hold', supp_7F}
patient_palette = {
    "Pt_1": "#FF0029",
    "Pt_2": "#377EB8",
    "Pt_3": "#66A61E",
    "Pt_4": "#984EA3",
    "Pt_5": "#00D2D5",
    "Pt_6": "#FF7F00",
    "Pt_7": "#AF8D00",
    "Pt_8": "#7F80CD",
    "Pt_9": "#B3E900",
    "Pt_10": "#C42E60",
    "Pt_11": "#A65628",
    "Pt_12": "#F781BF",
    "Pt_13": "#8DD3C7",
    "Pt_14": "#BEBADA",
    "Pt_15": "#FB8072",
    "Pt_16": "#80B1D3",
    "Pt_17": "#FDB462",
    "Pt_18": "#FCCDE5",
    "Pt_19": "#BC80BD",
    "Pt_20": "#FFED6F",
    "Pt_21": "#C4EAFF",
    "Pt_22": "#CF8C00",
    "Pt_23": "#1B9E77",
    "Pt_24": "#D95F02",
    "Pt_25": "#E7298A",
    "Pt_26": "#E6AB02",
    "Control": "#A6761D"
}

# Load single-cell object
dc_diff = pg.read_input(
    '/projects/home/tlchan/projects/ascites/dc_diff_data/clusterings/dc_diff_3_R3_500mg_20pm_multi_res/1.3/data/filter_qc/dc_diff_3_R3_500mg_20pm_1_3.zarr.zip')

patient_mapping = pd.read_csv("/projects/home/tlchan/projects/ascites/figure_panels/data/patient_name_remapping.csv")
patient_mapping = dict(zip(patient_mapping['patient_id'], patient_mapping['new_id']))

dc_diff.obs["patient"] = dc_diff.obs["patient"].replace(patient_mapping)
dc_diff.obs["patient"] = dc_diff.obs["patient"].replace("control", "Control")

fig = python_functions.plot_umap(lin_data=dc_diff,
                                 color="patient",
                                 palette=patient_palette,
                                 legend_loc=None)

plt.show()
# plt.savefig("/projects/home/tlchan/fig_panels/supp_7f.pdf")
plt.close(fig)
```

## Supplemental Figure 6G
```{r message = F, results = F, warning = F, fig.width = 4, fig.height = 8, supp_7G}
DC_palette <- c("DC_Diff1" = '#00916E',
                "DC_Diff2" = "#44DAE5",
                "DC_Diff3" = "#F88FBD",
                "DC_Diff4" = '#FFC857',
                "DC_Diff5" = '#B8ABE0')

diff_cell_type <- read.csv("/projects/home/tlchan/projects/ascites/results/abundance/dc_diff_data/dc_diff_3_R3_obs.csv") %>%
    mutate(DC_start = ifelse(DC_start == "DC1", "cDC1", DC_start)) %>%
    mutate(DC_start = ifelse(DC_start == "DC2", "cDC2", DC_start))

diff_cell_type <- diff_cell_type %>%
    filter(DC_start != "invalid") %>%
    group_by(lineage, DC_start) %>%
    summarize(count = n())

ggplot(diff_cell_type, aes(x = DC_start, y = count, fill = lineage)) +
    geom_bar(stat = "identity", position = "fill") +
    xlab("Starting DC subset") +
    ylab("% cell type") +
    labs(fill = "Lineage") +
    theme_classic(base_size = 23) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    scale_fill_manual(values = DC_palette)

# ggsave("/projects/home/tlchan/fig_panels/supp_7g.pdf", width = 4, height = 8)

# write.csv(diff_cell_type, "/projects/home/nealpsmith/projects/ascites/data/plot_data/fig_s6g.csv", row.names = FALSE)

```

## Supplemental Figure 6H
```{r message = F, results = F, warning = F, fig.width = 5, fig.height = 6, supp_7H}
markers <- read.csv("/projects/home/tlchan/projects/ascites/results/ova_correlation/w_peritoneal/asc_dc_with_diff_combo_markers.csv")

both_up <- markers[markers$dc_pb_lFC >= 1.25 & markers$diff_pb_lFC >= 1.25,]
ggplot(markers, aes(x = dc_pb_lFC, y = diff_pb_lFC)) +
    geom_point(data = both_up, color = "red") +
    geom_point(data = markers[markers$dc_pb_lFC < 1.25 | markers$diff_pb_lFC < 1.25,], color = "grey") +
    geom_label_repel(data = both_up, label = both_up$featurekey, force = 0.2, max.overlaps = Inf, size = 7) +
    xlab("log2FC of DC: PIGR, RORC") +
    ylab("log2FC of DC_Diff4") +
    theme_classic(base_size = 20)

# ggsave("/projects/home/tlchan/fig_panels/supp_7h.pdf", width = 5, height = 6)
```

## Supplemental Figure 6J-K

```{python fig_s7j_k, message = FALSE, warning = FALSE}

processed_data = pg.read_input("/projects/home/nealpsmith/projects/ascites/dc_diff_4/data/processed_data.zarr")

adata = processed_data.to_anndata()

sc.pl.umap(adata, color = ["Channel", "updated_clusters"], show = False, return_fig = False)

cats = ["Channel", "updated_clusters"]
fig, ax = plt.subplots(nrows=2, ncols=2)
ax = ax.ravel()
for num, c in enumerate(cats) :
    print(c)
    if c == "leiden_labels" :
        col_dict = dict(zip(sorted(set(adata.obs[c]), key = int),
                           adata.uns[f"{c}_colors"]))
        legend_elements = [Line2D([0], [0], marker='o', color=col_dict[cl], label=cl,
                                  markerfacecolor=col_dict[cl], markersize=7, lw=0) for cl in
                           sorted(set(adata.obs[c]), key = int)]
    else :
        col_dict = dict(zip(sorted(set(adata.obs[c])),
                            adata.uns[f"{c}_colors"]))
        legend_elements = [Line2D([0], [0], marker='o', color=col_dict[cl], label=cl,
                                  markerfacecolor=col_dict[cl], markersize=7, lw=0) for cl in
                           sorted(set(adata.obs[c]))]

    if len(legend_elements) > 6 :
        lcols = 2
        leg_loc = "on data"
    else :
        lcols = 1
        leg_loc = "none"

    plot = sc.pl.umap(adata, color=c,
                           legend_loc=leg_loc, show=False, ax=ax[num],
                           title="", legend_fontoutline=5)
    lgd = ax[num].legend(handles=legend_elements, loc='center left', fontsize=15,
                         bbox_to_anchor=(1, 0.5), frameon=False, ncol = lcols)
    ax[num].set_title(c)
    ax[num].set_rasterization_zorder(2)
for noplot in range(num + 1, len(ax)) :
    ax[noplot].axis("off")
fig = plt.gcf()
fig.set_size_inches(14, 8)
fig.tight_layout()
plt.show()
plt.close()
```

## Supplemental Figure 6L

```{r fig_s7l, message = FALSE, warning = FALSE, fig.height = 6, fig.width = 10}

obs <- read.csv("/projects/home/nealpsmith/projects/ascites/dc_diff_4/data/processed_data_obs.csv",
                row.names = 1)
clust_by_channel <- obs %>%
  group_by(updated_clusters, Channel) %>%
  summarise(n_cells = n()) %>%
  group_by(updated_clusters) %>%
  mutate(total_cells = sum(n_cells)) %>%
  mutate(perc_cells = n_cells / total_cells * 100)
clust_by_channel$updated_clusters <- factor(clust_by_channel$updated_clusters, levels = rev(unique(clust_by_channel$updated_clusters)))

ggplot(clust_by_channel, aes(x = perc_cells, y = updated_clusters, fill = Channel)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(values = c('#1f77b4', '#ff7f0e', '#2ca02c')) +
  xlab("% cells") + ylab("cluster") +
  ggtitle("% of cluster by channel") +
  theme_classic(base_size = 20)

write.csv(clust_by_channel, "/projects/home/nealpsmith/projects/ascites/data/plot_data/fig_s6l.csv", row.names = FALSE)


```

## Supplemental Figure 6M
```{python fig_s7m, message = FALSE, warning = FALSE}

genes =["RORC", "PRDM16", "PIGR", "S100B", "ACY3", "CCR6", "KIT", "CCR7", "ITGAE", "CLEC9A", "XCR1", "CD1C"]
genes = [g for g in genes if g in adata.var_names]
x_loc = np.min(adata.obsm["X_umap"][:,0]) - np.min(adata.obsm["X_umap"][:,0]) * 0.01
y_loc = np.min(adata.obsm["X_umap"][:,1]) - 0.4

fig, ax = plt.subplots(ncols = 3, nrows = 4, figsize = (10, 10))
ax = ax.ravel()

for num, gene in enumerate(genes) :
    # Calculate n cells and percent
    n_cells = adata[:, gene].X.count_nonzero()
    perc_cells = n_cells / len(adata) * 100
    perc_cells = round(perc_cells, 2)

    plot_df = pd.DataFrame(adata[:,gene].X.toarray(), columns = [gene], index = adata.obs_names)
    plot_df["x"] = adata.obsm["X_umap"][:, 0]
    plot_df["y"] = adata.obsm["X_umap"][:, 1]
    hb = ax[num].hexbin(plot_df["x"], plot_df["y"], C=plot_df[gene], cmap="YlOrRd", gridsize=120, edgecolors = "none")
    ax[num].get_xaxis().set_ticks([])
    ax[num].get_yaxis().set_ticks([])
    ax[num].spines['top'].set_visible(False)
    ax[num].spines['right'].set_visible(False)
    ax[num].set_title(gene, size = 25)
    ax[num].text(x_loc, y_loc, f"{n_cells} cells ({perc_cells}%)", style="italic")
    cb = fig.colorbar(hb, ax=ax[num], shrink=.75, aspect=10)
    cb.ax.set_title("Log(CPM)")
for noplot in range(num +1, len(ax)) :
    ax[noplot].axis("off")
fig.text(0.5, 0.03, 'UMAP1', va='center', size = 15)
fig.text(0.03, 0.5, 'UMAP2', va='center', rotation='vertical', size = 15)
fig.tight_layout()
plt.subplots_adjust(left = 0.1, bottom = 0.1)
plt.show()
plt.close()

```
