---
title: "Figure 5"
output: rmarkdown::github_document
---

## Set up

Load R libraries
```{r message = F, results = F, warning = F, load_r_libraries}
library(colorRamp2)
library(ComplexHeatmap)
library(cowplot)
library(ggpubr)
library(glue)
library(rstatix)
library(tidyverse)
library(VennDiagram)

setwd('/projects/home/tlchan/github_code/ascites/functions')
source('plot_deg.R')
source('plot_fgsea.R')
```

Load python libraries
```{python load_python_packages}
import matplotlib.pyplot as plt
import scanpy as sc
import squidpy as sq
```

## Figure 5B
```{r message = F, results = F, warning = F, fig.width = 14, fig.height = 6, fig_5B}
DC_palette <- c("DC1" = '#B8ABE0', "DC2" = '#7F3F98', "DC: PIGR, RORC" = '#FFC857', "CD14" = "#36565C")

CFSE_data <- read.csv("/projects/home/tlchan/projects/ascites/figure_panels/data/fig_5_data/combined_CFSE_stats.csv") %>%
    mutate(cell_category = gsub("newDC", "DC: PIGR, RORC", cell_category)) %>%
    mutate(cell_category = factor(cell_category, levels = c("CD14", "DC: PIGR, RORC", "DC1", "DC2")))

stats <- CFSE_data %>%
    filter(cell_category %in% c('DC: PIGR, RORC', 'CD14')) %>%
    t_test(log_CFSE_neg_perc ~ cell_category, paired = TRUE) %>%
    add_significance() %>%
    add_xy_position(x = "cell_category") %>%
    mutate(p_label = paste0("p = ", round(p, 3)))

ggplot(CFSE_data, aes(x = factor(cell_category), y = log_CFSE_neg_perc)) +
    geom_jitter(pch = 21, size = 5, width = 0.1, height = 0, aes(fill = cell_category)) +
    xlab("Cell category") +
    ylab("log(CFSE- percentage)") +
    scale_fill_manual(values = DC_palette) +
    stat_pvalue_manual(stats, label = "p_label", size = 7) +
    theme_classic(base_size = 22) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position = "none")

# ggsave("/projects/home/tlchan/fig_panels/fig_5b.pdf", width = 3.5, height = 7)
```

## Figure 5C
```{r message = F, results = F, warning = F, fig.width = 14, fig.height = 6, fig_5C}
cfse_neg_res <- read.csv("/projects/home/tlchan/projects/ascites/results/degs/mlr_data/lineage_level/combo_mlr_newDCvDC2_paired/combo_mlr_newDCvDC2_paired_CFSE_neg_de_by_newDCvDC2_paired_all_results.csv")
cfse_pos_res <- read.csv("/projects/home/tlchan/projects/ascites/results/degs/mlr_data/lineage_level/combo_mlr_newDCvDC2_paired/combo_mlr_newDCvDC2_paired_CFSE_pos_de_by_newDCvDC2_paired_all_results.csv")

mlr_meta <- read.csv('/projects/home/tlchan/projects/ascites/results/degs/mlr_data/pb_objects/combo_mlr_lineage_pseudobulk_meta.csv', row.names = 1) %>% mutate(DC_type = gsub("newDC", "DC: PIGR, RORC", DC_type))

cfse_neg_meta <- mlr_meta %>%
    filter(CFSE == "CFSE_neg") %>%
    filter(DC_type == "DC: PIGR, RORC" | DC_type == "DC2")
cfse_pos_meta <- mlr_meta %>%
    filter(CFSE == "CFSE_pos") %>%
    filter(DC_type == "DC: PIGR, RORC" | DC_type == "DC2")

# pdf("/projects/home/tlchan/fig_panels/fig_5c.pdf", width = 8, height = 8)
plot_lineage_deg(res = cfse_neg_res,
                 meta = cfse_neg_meta,
                 lin = "All CFSE- cells",
                 contrast = "DC_type",
                 ref_var = "DC2",
                 test_var = "DC: PIGR, RORC",
                 ref_color = "#7F3F98",
                 test_color = "#FFC857",
                 highlight_genes = c("OSM", "STMND1", "CCL4", "IFNG", "LAG3", "IL3", "SOCS1", "FGFBP2", "RORA", "CD28", "IL16"))
plot_lineage_deg(res = cfse_pos_res,
                 meta = cfse_pos_meta,
                 lin = "All CFSE+ cells",
                 contrast = "DC_type",
                 ref_var = "DC2",
                 test_var = "DC: PIGR, RORC",
                 ref_color = "#7F3F98",
                 test_color = "#FFC857",
                 highlight_genes = c("IFNG", "IFITM3", "IL13", "CCL4", "LAG3", "IL7R", "CTSL", "NR4A1", "CD27", "CD96"))
# dev.off()
```

## Figure 5D
```{r message = F, results = F, warning = F, fig.width = 14, fig.height = 6, fig_5D}
newDC_data <- read.csv("/projects/home/tlchan/projects/ascites/results/degs/mlr_data/mlr_newDCvDC2_paired_degs_summary.csv", row.names = 1) %>% rownames_to_column("gene_symbol")
newDC_up <- newDC_data %>%
    mutate(newDC_up = rowSums(. == "newDC")) %>%
    filter(newDC_up > 0) %>%
    pull("gene_symbol")
newDC_down <- newDC_data %>%
    mutate(newDC_down = rowSums(. == "DC2")) %>%
    filter(newDC_down > 0) %>%
    pull("gene_symbol")

DC1_data <- read.csv("/projects/home/tlchan/projects/ascites/results/degs/mlr_data/mlr_DC2vDC1_paired_degs_summary.csv", row.names = 1) %>% rownames_to_column("gene_symbol")
DC1_up <- DC1_data %>%
    mutate(DC1_up = rowSums(. == "DC1")) %>%
    filter(DC1_up > 0) %>%
    pull("gene_symbol")
DC1_down <- DC1_data %>%
    mutate(DC1_down = rowSums(. == "DC2")) %>%
    filter(DC1_down > 0) %>%
    pull("gene_symbol")

up_genes <- list(
    "DC1" = DC1_up,
    "DC: PIGR, RORC" = newDC_up
)

down_genes <- list(
    "DC1" = DC1_down,
    "DC: PIGR, RORC" = newDC_down
)

up_vd <- venn.diagram(x = up_genes,
                      fill = c("#B8ABE0", "#FFC857"),
                      alpha = 0.80,
                      lty = c(1, 2),
                      ext.text = FALSE,
                      cex = 2,
                      fontfamily = "sans",
                      cat.fontfamily = "sans",
                      cat.cex = 2,
                      filename = NULL,
                      disable.logging = TRUE)
down_vd <- venn.diagram(x = down_genes,
                        fill = c("#B8ABE0", "#FFC857"),
                        alpha = 0.80,
                        lty = c(1, 2),
                        ext.text = FALSE,
                        cex = 2,
                        fontfamily = "sans",
                        cat.fontfamily = "sans",
                        cat.cex = 2,
                        filename = NULL,
                        disable.logging = TRUE)

# pdf("/projects/home/tlchan/fig_panels/fig_5d.pdf", width = 10, height = 10)
plot_grid(up_vd)
plot_grid(down_vd)
# dev.off()
```

## Figure 5E
```{r message = F, results = F, warning = F, fig.width = 14, fig.height = 6, fig_5E}
setwd('/projects/home/tlchan/projects/ascites/results/degs/mlr_data/lineage_level')

lineage_list <- list(
    "combo_mlr" = "ALL",
    "combo_mlr_cd4" = "CD4",
    "combo_mlr_cd8" = "CD8"
)

# PREPARE DATA
all_res <- data.frame(baseMean = numeric(), log2FoldChange = numeric(), lfcSE = numeric(), stat = numeric(), pvalue = numeric(), padj = numeric(), gene_symbol = character(), lineage = character(), CFSE = character())

for (lin in names(lineage_list)) {
    for (cfse in c("CFSE_neg", "CFSE_pos")) {
        res <- read.csv(glue('{lin}_newDCvDC2_paired/{lin}_newDCvDC2_paired_{cfse}_de_by_newDCvDC2_paired_all_results.csv'))
        res$lineage <- lineage_list[lin]
        res$CFSE <- cfse

        all_res <- rbind(all_res, res)
    }
}

gene_markers <- read.csv('/projects/home/tlchan/projects/ascites/figure_panels/data/fig_5_data/fig_5e_heatmap_markers.csv')
heatmap_genes <- gene_markers$gene_symbol

# MAKE HEATMAP
lfc_mtx <- all_res %>%
    mutate(group = paste(lineage, CFSE, sep = "_")) %>%
    filter(gene_symbol %in% heatmap_genes) %>%
    select(log2FoldChange, gene_symbol, group) %>%
    pivot_wider(names_from = group, values_from = log2FoldChange) %>%
    column_to_rownames("gene_symbol") %>%
    mutate(across(everything(), ~replace_na(., 0))) %>%
    as.matrix()

# Cluster rows
row_clustering <- hclust(dist(lfc_mtx, method = "euclidean"), method = "ward.D2")
row_hc <- as.dendrogram(row_clustering)

# Heatmap color
heatmap_col_fun <- colorRamp2(c(min(lfc_mtx), 0, max(lfc_mtx)), c("purple", "black", "yellow"))

# Label genes
highlight_genes <- gene_markers %>%
    filter(highlight == TRUE) %>%
    pull(gene_symbol)

# Get the gene colors
gene_colors <- c()
for (gene in highlight_genes) {
    color <- ifelse(gene %in% c("IL5", "IL13", "IFNG"), "red", "black")
    gene_colors <- c(gene_colors, color)
}

gene_annot <- rowAnnotation(link = anno_mark(at = match(highlight_genes, rownames(lfc_mtx)),
                                             labels = highlight_genes,
                                             labels_gp = gpar(fontsize = 12, col = gene_colors)))

# Split CFSE
lfc_mtx <- lfc_mtx[, c("ALL_CFSE_pos", "CD8_CFSE_pos", "CD4_CFSE_pos", "ALL_CFSE_neg", "CD8_CFSE_neg", "CD4_CFSE_neg")]
sample_splits <- c(rep(c("CFSE+"), 3), rep(c("CFSE-"), 3))
colnames(lfc_mtx) <- rep(c("ALL", "CD8", "CD4"), 2)

# Split genes
gene_splits <- cutree(row_clustering, 2) %>%
    as.data.frame() %>%
    `colnames<-`(c("Direction"))
gene_splits <- gene_splits %>% mutate(Direction = ifelse(Direction == 1, "Up in DC2", "Up in DC: PIGR, RORC"))
gene_splits$Direction <- factor(gene_splits$Direction)

# Plot heatmap
hmap <- Heatmap(lfc_mtx,
                name = "log2FC",
                col = heatmap_col_fun,
                show_column_names = TRUE,
                show_row_names = FALSE,
                cluster_rows = row_hc,
                clustering_method_rows = "ward.D2",
                clustering_distance_rows = "euclidean",
                cluster_columns = FALSE,
                show_heatmap_legend = TRUE,
                heatmap_legend_param = list(direction = "horizontal"),
                column_split = sample_splits,
                column_title_gp = gpar(fontsize = 13),
                column_names_side = "bottom",
                column_names_rot = 90,
                column_names_centered = TRUE,
                right_annotation = gene_annot)

# pdf("/projects/home/tlchan/fig_panels/fig_5e.pdf", width = 3.5, height = 12)
draw(hmap, heatmap_legend_side = "bottom")
# dev.off()
```

## Figure 5F
```{python results = 'hold', fig_5F}
spatial_data = sc.read_h5ad('/projects/home/gdreynolds/ascites/xenium_LN/ln_processed_filtered.h5ad')

spatial_data.obs['annots'] = 'other'
spatial_data.obs.loc[spatial_data.obs['DCsteve_anno'].isin(
    ['CD4_naive', 'CD8_eff', 'Treg', 'CD8_naive', 'CD4_prolif', 'CD8_activated1',
     'CD8_activated2']), 'annots'] = 'T_cell_zone'
spatial_data.obs.loc[spatial_data.obs['DCsteve_anno'].isin(
    ['B_cell_mem', 'Plasma', 'B_cell_naive', 'B_cell_germinal', 'B_cell_prolif']), 'annots'] = 'B_cell_zone'
spatial_data.obs.loc[spatial_data.obs['DCsteve_anno'] == 'DC_new', 'annots'] = 'DC_RORC'

ax = sq.pl.spatial_scatter(spatial_data,
                           shape=None,
                           color=['annots'],
                           groups=['T_cell_zone', 'B_cell_zone'],
                           outline=True,
                           frameon=False,
                           size=0.5,
                           return_ax=True)
plt.show()
plt.close(fig)

ax = sq.pl.spatial_scatter(spatial_data,
                           shape=None,
                           color=['annots'],
                           groups=['DC_RORC'],
                           outline=True,
                           frameon=False,
                           size=50,
                           return_ax=True)
plt.show()
# plt.savefig("/projects/home/tlchan/fig_panels/fig_5f.pdf")
plt.close(fig)
```

## Figure 5G
```{r message = F, results = F, warning = F, fig.width = 14, fig.height = 6, fig_5G}
overenrichment_data <- read.csv("/projects/home/tlchan/projects/ascites/results/abundance/spatial_data/spatial_overenrichment_stats.csv")
overenrichment_data$sig <- ifelse(overenrichment_data$proportion > 1.5, 'sig', 'not_sig')

overenrichment_data <- overenrichment_data %>%
    filter(is.finite(proportion)) %>%
    arrange(proportion) %>%
    mutate(annots = factor(annots, levels = annots))

ggplot(overenrichment_data, aes(x = proportion, y = annots, color = sig)) +
    geom_point(size = 3) +
    geom_vline(xintercept = 1.5, linetype = "dotted", color = "black", size = 1.5) +
    ylab("Cluster") +
    xlab("Fold Change") +
    theme_bw() +
    scale_color_manual(values = c('#231F20', '#EF3D14')) +
    theme(legend.position = "none")

# ggsave("/projects/home/tlchan/fig_panels/fig_5g.pdf", width = 4.5, height = 8)
```


## Figure 5H
```{r message = F, results = F, warning = F, fig.width = 14, fig.height = 6, fig_5H}
niche_palette <- list(
    "Inside DC_RORC niche" = "#C42E60",
    "Outside DC_RORC niche" = "#A8B0B2"
)

cd4_prolif_data <- read.csv('/projects/home/tlchan/projects/ascites/figure_panels/data/violinplot_data/spatial_cd4_prolif_gene_exp.csv') %>%
    mutate(DC_RORC_niche = ifelse(DC_RORC_niche == "CD4_prolif_non_niche", "Outside DC_RORC niche", "Inside DC_RORC niche")) %>%
    mutate(DC_RORC_niche = factor(DC_RORC_niche, levels = c("Outside DC_RORC niche", "Inside DC_RORC niche"))) %>%
    mutate(Gene = factor(Gene, levels = c("CD3E", "CD4", "MKI67", "IFNG", "IL5", "IL13")))

stats <- cd4_prolif_data %>%
    group_by(Gene) %>%
    t_test(Count ~ DC_RORC_niche) %>%
    adjust_pvalue(method = "fdr") %>%
    add_significance() %>%
    add_xy_position(x = "DC_RORC_niche") %>%
    mutate(text_color = ifelse(p.adj < 0.05, "black", "gray"))

stats$clean_pvals <- sapply(stats$p, function(x) {
    if (x > 0.01) {
        return(as.character(round(x, 2)))
    } else if (x < 0.01 & x > 0.001) {
        return(as.character(round(x, 3)))
    } else {
        formatC(x, format = "e", digits = 0)
    }
})

ggplot(cd4_prolif_data, aes(x = DC_RORC_niche, y = Count)) +
    geom_violin(aes(fill = DC_RORC_niche), alpha = 0.75) +
    geom_jitter(width = 0.1, size = .5) +
    facet_wrap("Gene", scales = "free_y") +
    theme_classic(base_size = 20) +
    scale_fill_manual(values = niche_palette, guide = "none") +
    scale_y_continuous(expand = expansion(mult = c(0.05, 0.15))) +
    stat_pvalue_manual(data = stats, label = "p = {clean_pvals}", size = 6, color = "text_color") +
    scale_color_manual(values = c("black" = "#000000", "gray" = "#808080"), guide = "none") +
    theme(strip.text = element_text(face = "italic"), axis.text.x = element_blank())

# ggsave("/projects/home/tlchan/fig_panels/fig_5h.pdf", width = 4.5, height = 8)
```