---
title: "Cancer Figure"
output: rmarkdown::github_document
---

## Set up

Load R libraries
```{r message = F, results = F, warning = F, load_r_libraries}
library(circlize)
library(ComplexHeatmap)
library(ggpubr)
library(tidyverse)

library(reticulate)
use_python("/projects/home/tlchan/.conda/envs/myenv/bin/python")

setwd('/projects/home/tlchan/github_code/ascites/functions')
source('plot_fgsea.R')
```

Load python libraries
```{python load_python_packages}
import pegasus as pg

import sys
sys.path.append("/projects/home/tlchan/github_code/ascites/functions")
import python_functions
```
```{python results = 'hold', fig__A}
patient_palette = {
    "ASC_1": "#FF0029",
    "ASC_10": "#377EB8",
    "ASC_21": "#66A61E",
    "ASC_25": "#984EA3",
    "ASC_41": "#00D2D5",
    "ASC_43": "#FF7F00",
    "ASC_45": "#AF8D00",
    "ASC_46": "#7F80CD",
    "ASC_48": "#B3E900",
    "ASC_49": "#C42E60",
    "ASC_5": "#A65628",
    "ASC_52": "#F781BF",
    "ASC_57": "#8DD3C7",
    "ASC_61": "#BEBADA",
    "ASC_62": "#FB8072",
    "ASC_65": "#80B1D3",
    "ASC_66": "#FDB462",
    "ASC_67": "#FCCDE5",
    "GC-PC_10": "#BC80BD",
    "GC-PC_11": "#FFED6F",
    "GC-PC_17": "#C4EAFF",
    "GC-PC_5": "#CF8C00",
    "GC-PC_7": "#1B9E77"
}
cancer_data = pg.read_input(
    '/projects/home/tlchan/projects/ascites/second_data_freeze/clusterings/ascites_cancer_R3_300mg_20pm_multi_res/1.3/data/pseudobulk/ascites_cancer_R3_300mg_20pm_1_3_complete_with_pb.zarr.zip')
cancer_data.obs["Patient"] = cancer_data.obs["patient_id"]
cancer_fig, cancer_ax = plt.subplots(1)
cancer_umap = sc.pl.umap(adata=cancer_data.to_anndata(),
                         color="Patient",
                         use_raw=True,
                         palette=patient_palette,
                         # legend_loc="on data",
                         legend_fontoutline=5,
                         title="",
                         show=False,
                         ax=cancer_ax)
cancer_fig = plt.gcf()
cancer_fig.set_size_inches(6, 3.7)
cancer_fig.tight_layout()
cancer_ax.set_rasterization_zorder(2)
plt.show()
plt.savefig("/projects/home/tlchan/fig_panels/fig__a.pdf")
plt.close()
```

```{r message = F, results = F, warning = F, fig.width = 5, fig.height = 8, fig__B}
cancer_counts_filepath <- "/projects/home/tlchan/projects/ascites/second_data_freeze/clusterings/ascites_cancer_R3_300mg_20pm_multi_res/1.3/data/pseudobulk/ascites_cancer_R3_300mg_20pm_1_3_pseudobulk_counts.csv"
cancer_meta_filepath <- "/projects/home/tlchan/projects/ascites/second_data_freeze/clusterings/ascites_cancer_R3_300mg_20pm_multi_res/1.3/data/pseudobulk/ascites_cancer_R3_300mg_20pm_1_3_pseudobulk_meta.csv"

# Normalize counts
counts <- read_csv(cancer_counts_filepath) %>% column_to_rownames("featurekey")
norm_counts <- apply(counts, 2, function(c) {
    n_total <- sum(c)
    per_100k <- (c * 1000000) / n_total
    return(per_100k)
})
norm_counts <- log1p(norm_counts)

testing_csv <- "/projects/home/tlchan/projects/ascites/second_data_freeze/data/gene_programs/canon_gene_sets.csv"
testing_data <- read_csv(testing_csv, show_col_types = FALSE) %>%
    filter(grepl("NatureMed", program_name)) %>%
    select("program_name", "genes") %>%
    column_to_rownames("program_name")

# Get gene mapping
gastric_genes <- unlist(strsplit(testing_data["NatureMed_gastric", "genes"], split = ",")) %>%
    enframe() %>%
    rename(program_name = "name", gene = "value") %>%
    mutate(program_name = "gastric")
colon_genes <- unlist(strsplit(testing_data["NatureMed_colon", "genes"], split = ",")) %>%
    enframe() %>%
    rename(program_name = "name", gene = "value") %>%
    mutate(program_name = "colon")
gene_df <- rbind(gastric_genes, colon_genes)

# Make and scale heatmap matrix
heatmap_mtx <- norm_counts[gene_df$gene,]
heatmap_mtx <- t(scale(t(heatmap_mtx)))

heatmap_col_fun <- colorRamp2(c(min(heatmap_mtx), 0, max(heatmap_mtx)), c("purple", "black", "yellow"))

# This creates the dendrogram for the samples, using euclidean distance and Ward method. These can def be changed. see documentation
clustering_cols <- hclust(dist(t(heatmap_mtx), method = "euclidean"), method = "ward.D2")
col_hc <- as.dendrogram(clustering_cols)

# Make gene bar
genes <- rownames(heatmap_mtx)
programs <- paste(lapply(genes, function(gene) gene_df$program_name[match(gene, gene_df$gene)]), sep = " ", collapse = NULL)

gene_bar <- rowAnnotation(program = programs,
                          col = list(program = c('gastric' = '#fff2ac', 'colon' = '#fd9941')),
                          show_legend = TRUE,
                          show_annotation_name = FALSE)

# This creates the dendrogram for the genes
clustering_rows <- hclust(dist(heatmap_mtx, method = "euclidean"), method = "ward.D2")
row_hc <- as.dendrogram(clustering_rows)

hmap <- Heatmap(heatmap_mtx,
                name = "z-score",
                col = heatmap_col_fun,
                right_annotation = gene_bar,
                show_column_names = TRUE,
                column_names_gp = gpar(fontsize = 20),
                show_row_names = TRUE,
                row_names_gp = gpar(cex = 0.5, fontsize = 20),
                cluster_columns = col_hc,
                cluster_rows = row_hc,
                show_heatmap_legend = TRUE,
                column_title = "Patient",
                row_title = "Genes")


pdf("/projects/home/tlchan/fig_panels/fig__b.pdf", width = 20, height = 12)
draw(hmap, column_title = "Cancer: NatureMed Classification", column_title_gp = grid::gpar(fontsize = 22))
dev.off()
```


## Figure _C
```{r message = F, results = F, warning = F, fig.width = 6, fig.height = 6, fig__C}
cancer_res <- read.csv('/projects/home/tlchan/projects/ascites/second_data_freeze/data/degs/lineage_level/log_survival/cancer_de_by_log_survival_all_results.csv')
cancer_meta <- read.csv("/projects/home/tlchan/projects/ascites/second_data_freeze/data/degs/pb_objects/cancer_lineage_pseudobulk_meta.csv", row.names = 1)

cancer_meta <- cancer_meta %>%
        filter(!is.na(survival)) %>%
        mutate(log_survival = log(survival)) %>%
        mutate(sex = factor(sex, levels = c('M', 'F')))

plot_lineage_deg(res = cancer_res,
                 meta = cancer_meta,
                 lin = "Cancer",
                 contrast = "log_survival")
ggsave("/projects/home/tlchan/fig_panels/fig__d.pdf", width = 8, height = 8)
```

```{r message = F, results = F, warning = F, fig.width = 5, fig.height = 8, fig__D}
counts_filepath <- "/projects/home/tlchan/projects/ascites/second_data_freeze/clusterings/ascites_cancer_R3_300mg_20pm_multi_res/1.3/data/pseudobulk/ascites_cancer_R3_300mg_20pm_1_3_pseudobulk_counts.csv"
meta_filepath <- "/projects/home/tlchan/projects/ascites/second_data_freeze/clusterings/ascites_cancer_R3_300mg_20pm_multi_res/1.3/data/pseudobulk/ascites_cancer_R3_300mg_20pm_1_3_pseudobulk_meta.csv"

counts <- read_csv(counts_filepath)
counts <- counts %>%
    column_to_rownames(var = "featurekey") %>%
    apply(2, function(c) {
        n_total <- sum(c)
        per_100k <- (c * 1000000) / n_total
        return(per_100k)
    }) %>%
    as.data.frame
counts <- log1p(counts)
counts <- counts %>% filter(rownames(counts) == "DEFB1")
meta <- read.csv(meta_filepath, row.names = 1)
counts <- dplyr::select(counts, rownames(meta))

meta_cluster <- meta %>% filter(n_cells >= 10)
counts_cluster <- counts[, rownames(meta_cluster)]
counts_cluster <- as.data.frame(t(counts_cluster))
counts_cluster$sample <- rownames(counts_cluster)
meta_cluster$sample <- rownames(meta_cluster)
plot_data <- merge(counts_cluster, meta_cluster, by = "sample")

ggplot(plot_data, aes(x = log10(survival), y = DEFB1, label = patient_id)) +
    geom_point(pch = 21, size = 2) +
    geom_smooth(method = "lm", formula = y ~ x) +
    stat_cor() +
    geom_text_repel() +
    xlab("log(Days survival)") +
    ylab("log1p(DEFB1 pseudobulk count)") +
    ggtitle(glue("Cancer DEFB1 by survival")) +
    theme_classic(base_size = 12)
```

## Figure _E
```{python results = 'hold', fig__E}
cancer_data = pg.read_input("/projects/home/tlchan/projects/ascites/data_cite_objects/cancer.zarr.zip")

python_functions.plot_feature(lin_data=cancer_data,
                              genes=['DEFB1', 'CCL20'],
                              ncol=1,
                              nrow=2)
```