---
title: "Supplemental Figure 8"
output: rmarkdown::github_document
---

## Set up

Load R libraries
```{r message = F, results = F, warning = F, load_r_libraries}
library(colorspace)
library(glue)
library(openxlsx)
library(tidyverse)
```

## Supplemental Figure 8A
```{r message = F, results = F, warning = F, fig.width = 25, fig.height = 15.5, supp_8A}
# Use Reds
reds_colormap <- read.table('/projects/home/tlchan/util/cmaps/reds_cmap.txt', header = FALSE)
reds_hex <- apply(reds_colormap, 1, function(row) {
    rgb(row[1], row[2], row[3], maxColorValue = 1)
})

gene_order <- read.xlsx('/projects/home/tlchan/projects/ascites/figure_panels/data/spatial_dotplot_markers.xlsx', sheet = "LINEAGE") %>%
    filter(!is.na(genes)) %>%
    pull(genes) %>%
    strsplit(",") %>%
    unlist()

cluster_order <- c("CD4_naive", "CD4_prolif", "Treg", "CD8_naive", "CD8_1", "CD8_2", "NK", "NK_prolif", "B_cell_naive",
                   "B_cell_mem", "B_cell_germinal", "B_cell_prolif", "Plasma", "Plasma_prolif", "cDC1", "cDC2",
                   "cDC2_prolif", "DC_CCR7", "DC_RORC", "pDC", "Mac", "Mast_cell", "Endothelium_lymph",
                   "Endothelium_vascular", "Endothelium_sinusoidal", "Follicular_DC", "HEV")

lin_gex <- read.csv(glue('/projects/home/tlchan/projects/ascites/figure_panels/data/dotplot_data/spatial_gene_exp.csv')) %>%
    mutate(Gene = factor(Gene, levels = gene_order), Cluster = factor(Cluster, levels = cluster_order))

ggplot(lin_gex, aes(x = Gene, y = fct_rev(Cluster), fill = Count, size = Percent_Expressed)) +
    geom_point(color = "black", shape = 21) +
    ylab('Cluster') +
    labs(size = "% Expressed", fill = "Scaled expression") +
    scale_fill_gradientn(colors = reds_hex) +
    lims(size = c(0, 100)) +
    theme_light(base_size = 25) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, face = "italic")) +
    theme(legend.key.size = unit(.4, "cm"), legend.title = element_text(size = 20), legend.text = element_text(size = 12))
width <- length(unique(lin_gex$Gene)) / 4 + 7.5
height <- length(unique(lin_gex$Cluster)) / 2 + 2

# ggsave(glue("/projects/home/tlchan/fig_panels/supp_8a.pdf"), width = width, height = height)
```


## Supplemental Figure 8B
```{r message = F, results = F, warning = F, fig.width = 8, fig.height = 8, supp_8B}
corr_mat <- read.csv("/projects/home/tlchan/projects/ascites/results/spearman/spatial_data/spatial_dc_with_pigr_dc_corr_long.csv")

corr_mat <- corr_mat %>%
    mutate(Nor = (value - min(value)) / (max(value) - min(value)))

corr_mat <- corr_mat %>%
    mutate(dc_clusters = factor(dc_clusters, levels = rev(c('cDC1: CLEC9A, XCR1', 'cDC2: CD1C, CD33-hi',
                                                            'cDC2: CD1C, CD33-lo', 'cDC3: CD1C, VCAN',
                                                            'cDC: CD1C, FCGR3A', 'cDC: IL1R2, NR4A1',
                                                            'mregDCs: LAMP3, CCR7', 'DC: PIGR, RORC',
                                                            'cDC: SIGLEC6, IL22RA2', 'pDC: LILRA4, IL3RA')))) %>%
    mutate(spatial_clusters = factor(spatial_clusters, levels = c('cDC1', 'cDC2', 'cDC2_prolif', 'DC_CCR7', 'DC_RORC', 'pDC')))

ggplot(corr_mat, aes(x = spatial_clusters, y = dc_clusters, fill = Nor)) +
    geom_tile(colour = "black", size = 0.5) +
    xlab("Spatial DC subsets") +
    ylab("Ascites DC subsets") +
    scale_fill_continuous_diverging(palette = "Blue-Red 3", limits = c(0, 1), mid = 0.5, name = "Normalized Spearman") +
    scale_x_discrete(expand = c(0, 0)) +
    scale_y_discrete(expand = c(0, 0)) +
    coord_fixed() +
    theme_classic(base_size = 20) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

# ggsave(glue("/projects/home/tlchan/fig_panels/supp_8b.pdf"), width = 8, height = 8)
```