---
title: "Supplemental Cancer"
output: rmarkdown::github_document
---

## Set up

Load R libraries
```{r message = F, results = F, warning = F, load_r_libraries}
library(circlize)
library(ComplexHeatmap)
library(tidyverse)
```

## Figure 1A
```{r message = F, results = F, warning = F, fig.width = 12, fig.height = 6, fig_1A}
cancer_counts_filepath <- "/projects/home/tlchan/projects/ascites/second_data_freeze/clusterings/ascites_cancer_R3_300mg_20pm_multi_res/1.3/data/pseudobulk/ascites_cancer_R3_300mg_20pm_1_3_pseudobulk_counts.csv"
cancer_meta_filepath <- "/projects/home/tlchan/projects/ascites/second_data_freeze/clusterings/ascites_cancer_R3_300mg_20pm_multi_res/1.3/data/pseudobulk/ascites_cancer_R3_300mg_20pm_1_3_pseudobulk_meta.csv"

# Normalize counts
counts <- read_csv(cancer_counts_filepath) %>% column_to_rownames("featurekey")
norm_counts <- apply(counts, 2, function(c) {
    n_total <- sum(c)
    per_100k <- (c * 1000000) / n_total
    return(per_100k)
})
norm_counts <- log1p(norm_counts)

testing_csv <- "/projects/home/tlchan/projects/ascites/second_data_freeze/data/gene_programs/canon_gene_sets.csv"
testing_data <- read_csv(testing_csv, show_col_types = FALSE) %>%
    filter(grepl("NatureMed", program_name)) %>%
    select("program_name", "genes") %>%
    column_to_rownames("program_name")

# Get gene mapping
gastric_genes <- unlist(strsplit(testing_data["NatureMed_gastric", "genes"], split = ",")) %>%
    enframe() %>%
    rename(program_name = "name", gene = "value") %>%
    mutate(program_name = "gastric")
colon_genes <- unlist(strsplit(testing_data["NatureMed_colon", "genes"], split = ",")) %>%
    enframe() %>%
    rename(program_name = "name", gene = "value") %>%
    mutate(program_name = "colon")
gene_df <- rbind(gastric_genes, colon_genes)

# Make and scale heatmap matrix
heatmap_mtx <- norm_counts[gene_df$gene,]
heatmap_mtx <- t(scale(t(heatmap_mtx)))

heatmap_col_fun <- colorRamp2(c(min(heatmap_mtx), 0, max(heatmap_mtx)), c("purple", "black", "yellow"))

# Make patient bar
patients <- colnames(heatmap_mtx)

patient_col_fun <- c("#FFFF00", "#1CE6FF", "#FF34FF", "#FF4A46", "#008941", "#006FA6", "#A30059", "#FFDBE5", "#7A4900",
                     "#0000A6", "#63FFAC", "#B79762", "#004D43", "#8FB0FF", "#997D87", "#5A0007", "#809693", "#6A3A4C",
                     "#1B4400", "#4FC601", "#3B5DFF", "#4A3B53", "#FF2F80")
names(patient_col_fun) <- patients

patient_bar <- HeatmapAnnotation(
    patient_id = patients,
    col = list(patient_id = patient_col_fun),
    show_legend = TRUE,
    show_annotation_name = FALSE
)

# This creates the dendrogram for the samples, using euclidean distance and Ward method. These can def be changed. see documentation
clustering_cols <- hclust(dist(t(heatmap_mtx), method = "euclidean"), method = "ward.D2")
col_hc <- as.dendrogram(clustering_cols)

# Make gene bar
genes <- rownames(heatmap_mtx)
programs <- paste(lapply(genes, function(gene) gene_df$program_name[match(gene, gene_df$gene)]), sep = " ", collapse = NULL)

gene_bar <- rowAnnotation(
    program = programs,
    col = list(program = c('gastric' = '#fff2ac', 'colon' = '#fd9941')),
    show_legend = TRUE,
    show_annotation_name = FALSE
)

# This creates the dendrogram for the genes
clustering_rows <- hclust(dist(heatmap_mtx, method = "euclidean"), method = "ward.D2")
row_hc <- as.dendrogram(clustering_rows)

hmap <- Heatmap(heatmap_mtx, name = "z-score", col = heatmap_col_fun,
                top_annotation = patient_bar, right_annotation = gene_bar, show_column_names = TRUE,
                show_row_names = TRUE, row_names_gp = gpar(cex = 0.5),
                cluster_columns = col_hc, cluster_rows = row_hc,
                show_heatmap_legend = TRUE, column_title = "Patient",
                row_title = "Genes")

draw(hmap,
     column_title = "Cancer: NatureMed Classification",
     column_title_gp = grid::gpar(fontsize = 16))
```
