---
title: "Cancer Figure"
output: rmarkdown::github_document
---

## Set up

Load R libraries
```{r message = F, results = F, warning = F, load_r_libraries}
# load packages
library(tidyverse)
library(glue)
library(ComplexHeatmap)
library(reticulate)
use_python("/projects/home/tlchan/.conda/envs/myenv/bin/python")

setwd('/projects/home/tlchan/github_code/ascites/functions')
source('plot_fgsea.R')
```

Load python libraries
```{python load_python_packages}
import pegasus as pg
import scanpy as sc
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
```

## Figure 1A
```{python results = 'hold', fig_1A}
mpl.rcParams['pdf.fonttype'] = 42

patient_palette = {
    "ASC_1": "#FF0029",
    "ASC_10": "#377EB8",
    "ASC_21": "#66A61E",
    "ASC_25": "#984EA3",
    "ASC_41": "#00D2D5",
    "ASC_43": "#FF7F00",
    "ASC_45": "#AF8D00",
    "ASC_46": "#7F80CD",
    "ASC_48": "#B3E900",
    "ASC_49": "#C42E60",
    "ASC_5": "#A65628",
    "ASC_52": "#F781BF",
    "ASC_57": "#8DD3C7",
    "ASC_61": "#BEBADA",
    "ASC_62": "#FB8072",
    "ASC_65": "#80B1D3",
    "ASC_66": "#FDB462",
    "ASC_67": "#FCCDE5",
    "GC-PC_10": "#BC80BD",
    "GC-PC_11": "#FFED6F",
    "GC-PC_17": "#C4EAFF",
    "GC-PC_5": "#CF8C00",
    "GC-PC_7": "#1B9E77"
}
cancer_data = pg.read_input(
    '/projects/home/tlchan/projects/ascites/second_data_freeze/clusterings/ascites_cancer_R3_300mg_20pm_multi_res/1.3/data/pseudobulk/ascites_cancer_R3_300mg_20pm_1_3_complete_with_pb.zarr.zip')
cancer_data.obs["Patient"] = cancer_data.obs["patient_id"]

cancer_fig, cancer_ax = plt.subplots(1)
cancer_umap = sc.pl.umap(adata=cancer_data.to_anndata(),
                         color="Patient",
                         use_raw=True,
                         palette=patient_palette,
                         # legend_loc="on data",
                         legend_fontoutline=5,
                         title="",
                         show=False,
                         ax=cancer_ax)
cancer_fig = plt.gcf()
cancer_fig.set_size_inches(6, 3.7)
cancer_fig.tight_layout()
cancer_ax.set_rasterization_zorder(2)
plt.show()
plt.close()
```

## Figure 1B
```{python results = 'hold', fig_1B}
mpl.rcParams['pdf.fonttype'] = 42

ncol = 4
nrow = 2
genes = ['EPCAM', 'DCN', 'MKI67', 'HLA-DRA', 'ERBB2', 'CLDN18', 'EGFR', 'cite_EGFR']

lineage_data = pg.read_input("/projects/home/tlchan/data_objects/cancer.zarr.zip")

# get umap coordinates for base
umap_coords = pd.DataFrame(lineage_data.obsm['X_umap'], columns=['x', 'y'])
x = umap_coords['x']
y = umap_coords['y']

# Set up figure structure
fig_size = (5 * ncol, 4 * nrow)
fig, axes = plt.subplots(nrows=nrow, ncols=ncol, figsize=fig_size,
                         sharex=True, sharey=True)
ax = axes.ravel()

# Plot for each gene
for num, gene in enumerate(genes):
    # get counts for each gene
    norm_counts = lineage_data[:, gene].copy().get_matrix('X').todense().transpose()
    norm_counts = np.squeeze(np.asarray(norm_counts))

    if norm_counts.size == 0:  # ie. All empty/zero in sparce matrix
        norm_counts = np.zeros(norm_counts.shape[1])

    # Get n cells and perc cells
    ncells = (norm_counts != 0).sum()
    pcells = ncells / norm_counts.shape[0]

    if gene.startswith('cite_'):
        cmap = 'PuBu'
    else:
        cmap = 'YlOrRd'

    # Create heatmap
    hb = ax[num].hexbin(x=x,
                        y=y,
                        C=norm_counts,
                        cmap=cmap,
                        gridsize=150,
                        edgecolors="none")

    # Add percent expression
    ax[num].annotate(f'{ncells:,} ({pcells:.1%}) cells',
                     xy=(0.01, 0), xycoords='axes fraction',
                     fontsize=10,
                     horizontalalignment='left',
                     verticalalignment='bottom')

    # Add axes and colorbar information
    cb = fig.colorbar(hb, ax=ax[num], shrink=.75, aspect=10)
    cb.ax.set_title('logCPM', loc='left', fontsize=14)
    ax[num].set_title(gene, fontsize=18)
    ax[num].tick_params(left=False, labelleft=False,
                        bottom=False, labelbottom=False)
    if (num + ncol) % ncol == 0:
        # Start of row
        ax[num].set_ylabel('UMAP2', fontsize=18)
    if nrow == 1:
        # Only one row
        ax[num].set_xlabel('UMAP1', fontsize=18)
    elif num > (len(genes) - ncol - 1):
        # Last row if more than one row
        ax[num].set_xlabel('UMAP1', fontsize=18)

    # Rasterize
    ax[num].set_rasterization_zorder(2)

for i in range(len(ax) - (len(ax) - len(genes)), len(ax)):
    ax[i].set_axis_off()
fig.tight_layout()
plt.show()
plt.close()
```

## Figure 1C
```{r message = F, results = F, warning = F, fig.width = 5, fig.height = 8, fig_1C}
# Make cancer heatmap
all_fgsea <- read.csv("/projects/home/tlchan/projects/ascites/second_data_freeze/data/gene_programs/FGSEA_scores/canonical_combo_fgsea.csv")

cancer_fgsea <- all_fgsea %>%
    filter(lineage == "cancer") %>%
    select("pathway", "NES", "padj", "variable")
nes_mtx <- cancer_fgsea %>%
    select("pathway", "NES", "variable") %>%
    pivot_wider(names_from = variable, values_from = NES) %>%
    column_to_rownames("pathway")
padj_mtx <- cancer_fgsea %>%
    select("pathway", "padj", "variable") %>%
    pivot_wider(names_from = variable, values_from = padj) %>%
    column_to_rownames("pathway")

stopifnot(identical(rownames(nes_mtx), rownames(padj_mtx)))
stopifnot(identical(colnames(nes_mtx), colnames(padj_mtx)))

clustering_cols <- hclust(dist(t(nes_mtx), method = "euclidean"), method = "ward.D2")
col_hc <- as.dendrogram(clustering_cols)

clustering_rows <- hclust(dist(nes_mtx, method = "euclidean"), method = "ward.D2")
row_hc <- as.dendrogram(clustering_rows)

fgsea_hmap <- Heatmap(nes_mtx,
                      name = "NES",
                      show_column_names = TRUE,
                      show_row_names = TRUE,
                      row_names_gp = gpar(cex = 0.5),
                      cluster_columns = FALSE,
                      cluster_rows = FALSE,
                      show_heatmap_legend = TRUE,
                      column_title = "Variable",
                      row_title = "Program",
                      cell_fun = function(j, i, x, y, width, height, fill) {
                          if (padj_mtx[i, j] < 0.05)
                              grid.text("•", x, y, gp = gpar(fontsize = 20))
                      })

draw(fgsea_hmap,
     column_title = glue("Cancer FGSEA"),
     column_title_gp = grid::gpar(fontsize = 16))
```

## Figure 1D
```{r message = F, results = F, warning = F, fig.width = 5, fig.height = 8, fig_1D}
gene_sets <- read.csv("/projects/home/tlchan/projects/ascites/second_data_freeze/data/gene_programs/canon_gene_sets.csv")

EMT_gs <- gene_sets %>%
    filter(program_name == "EMT") %>%
    pull(genes) %>%
    str_split(",")

cancer_B2M_data <- read.csv(glue('cancer/cancer_de_by_B2M_2v0_all_results.csv'))
cancer_fgsea <- read.csv("/projects/home/tlchan/projects/ascites/second_data_freeze/data/gene_programs/FGSEA_scores/by_lineage/cancer_combo_fgsea.csv")
EMT_fgsea <- cancer_fgsea %>%
    filter(pathway == "EMT") %>%
    filter(variable == "B2M_2v0")

plot_fgsea(EMT_fgsea, cancer_B2M_data, EMT_gs, "cancer", "B2M_2v0", "EMT")
```