---
title: "TBD"
---

## DC TISSUE TYPE VOLCANO
```{r message = F, results = F, warning = F}
dc_res <- read.csv('/projects/home/tlchan/projects/ascites/second_data_freeze/data/degs/lineage_level/tissue_type/dc_de_by_tissue_type_all_results.csv')
dc_meta <- read.csv("/projects/home/tlchan/projects/ascites/second_data_freeze/data/degs/pb_objects/dc_lineage_pseudobulk_meta.csv", row.names = 1)

dc_meta <- dc_meta %>% filter(tissue_type == "blood" | tissue_type == "ascites") %>%
        mutate(tissue_type = factor(tissue_type, levels = c("blood", "ascites"))) %>%
        mutate(sex = factor(sex, levels = c('M', 'F')))

plot_lineage_deg(res = dc_res,
                  meta = dc_meta,
                  lin = "DC",
                  contrast = "tissue_type",
                  ref_var = "blood",
                  test_var = "ascites")
```

## DC FEATURE PLOTS
```{python results = 'hold'}
dc_data = pg.read_input(
    '/projects/home/tlchan/projects/ascites/second_data_freeze/clusterings/ascites_dc_R8_300mg_20pm_harm_channel_multi_res/1.1/data/pseudobulk/ascites_dc_R8_300mg_20pm_harm_channel_1_1_complete_with_pb.zarr.zip')

python_functions.plot_feature_by_tissue_type(lin_data=dc_data,
                                             genes=["CXCL16", "IL18"])
```

## DC 10 FGSEA
```{r message = F, results = F, warning = F}
select_results <- read.csv("/projects/home/tlchan/projects/ascites/second_data_freeze/data/gsea/select_split_msigdb_fgsea_results.csv")

select_sets <- select_results %>%
    select(pathway) %>%
    distinct() %>%
    pull()

select_vars <- select_results %>%
    select(variable) %>%
    distinct() %>%
    pull()

split_fgsea <- read.csv("/projects/home/tlchan/projects/ascites/second_data_freeze/data/gsea/gsea_scores/msigdb_split_fgsea.csv") %>%
    filter(pathway %in% select_sets) %>%
    filter(variable %in% select_vars) %>%
    filter(lineage == "dc") %>%
    filter(tissue_type == "ascites") %>%
    filter(cluster == "10")

dc10_fgsea <- split_fgsea %>%
    select("pathway", "NES", "padj", "variable")
nes_mtx <- dc10_fgsea %>%
    select("pathway", "NES", "variable") %>%
    pivot_wider(names_from = variable, values_from = NES) %>%
    column_to_rownames("pathway")
padj_mtx <- dc10_fgsea %>%
    select("pathway", "padj", "variable") %>%
    pivot_wider(names_from = variable, values_from = padj) %>%
    column_to_rownames("pathway")

stopifnot(identical(rownames(nes_mtx), rownames(padj_mtx)))
stopifnot(identical(colnames(nes_mtx), colnames(padj_mtx)))

clustering_cols <- hclust(dist(t(nes_mtx), method = "euclidean"), method = "ward.D2")
col_hc <- as.dendrogram(clustering_cols)

clustering_rows <- hclust(dist(nes_mtx, method = "euclidean"), method = "ward.D2")
row_hc <- as.dendrogram(clustering_rows)

fgsea_hmap <- Heatmap(nes_mtx,
                      name = "NES",
                      show_column_names = TRUE,
                      column_names_gp = gpar(fontsize = 16),
                      show_row_names = TRUE,
                      row_names_gp = gpar(cex = 0.5, fontsize = 16),
                      cluster_columns = FALSE,
                      cluster_rows = FALSE,
                      show_heatmap_legend = TRUE,
                      column_title = "Variable",
                      row_title = "Program",
                      cell_fun = function(j, i, x, y, width, height, fill) {
                          if (padj_mtx[i, j] < 0.05)
                              grid.text("•", x, y, gp = gpar(fontsize = 20))
                      })

draw(fgsea_hmap,
     column_title = glue("DC 10 FGSEA"),
     column_title_gp = grid::gpar(fontsize = 16))
```

## DC FGSEA
```{r message = F, results = F, warning = F}
dc_fgsea <- read.csv("/projects/home/tlchan/projects/ascites/second_data_freeze/data/gsea/select_split_msigdb_fgsea_results.csv") %>% mutate(gene_set = tolower(map(str_split(pathway, "_"), 1)))
gene_sets <- gmtPathways(glue("/projects/home/tlchan/projects/ascites/second_data_freeze/data/gsea/gene_sets/hallmark_symbols.gmt"))

gly_fgsea <- dc_fgsea %>%
    filter(pathway == "HALLMARK_GLYCOLYSIS") %>%
    filter(variable == "survival")

dc_c10_survival_data <- read.csv(glue('/projects/home/tlchan/projects/ascites/ascites_deg_results/dc/dc_ascites_de_by_survival_all_results.csv')) %>%
    filter(cluster == 10) %>%
    select(c("gene_symbol", "stat")) %>%
    na.omit() %>%
    distinct() %>%
    group_by(gene_symbol) %>%
    summarize(stat = mean(stat)) %>%
    deframe()

plot_fgsea(gly_fgsea, dc_c10_survival_data, gene_sets[["HALLMARK_GLYCOLYSIS"]], "DC cluster 10", "survival", "HALLMARK Glycolysis")

ifng_fgsea <- dc_fgsea %>%
    filter(pathway == "HALLMARK_INTERFERON_GAMMA_RESPONSE") %>%
    filter(variable == "survival")

dc_c10_survival_data <- read.csv(glue('/projects/home/tlchan/projects/ascites/ascites_deg_results/dc/dc_ascites_de_by_survival_all_results.csv')) %>%
    filter(cluster == 10) %>%
    select(c("gene_symbol", "stat")) %>%
    na.omit() %>%
    distinct() %>%
    group_by(gene_symbol) %>%
    summarize(stat = mean(stat)) %>%
    deframe()

plot_fgsea(ifng_fgsea, dc_c10_survival_data, gene_sets[["HALLMARK_INTERFERON_GAMMA_RESPONSE"]], "DC cluster 10", "survival", "HALLMARK Interferon Gamma Response")
```
```{r message = F, results = F, warning = F}
dc_fgsea <- read.csv("/projects/home/tlchan/projects/ascites/second_data_freeze/data/dc_analysis/mreg/mreg_fgsea_results.csv")
gene_sets <- read.csv("/projects/home/tlchan/projects/ascites/second_data_freeze/data/dc_analysis/mreg/gene_sets.csv")

cDC2_fgsea <- dc_fgsea %>%
    filter(pathway == "cDC2") %>%
    filter(variable == "B2M_2v0")

dc_mreg_B2M_data <- read.csv(glue('/projects/home/tlchan/projects/ascites/ascites_deg_results/dc_mregs/dc_mregs_de_by_B2M_2v0_all_results.csv')) %>%
    select(c("gene_symbol", "stat")) %>%
    na.omit() %>%
    distinct() %>%
    group_by(gene_symbol) %>%
    summarize(stat = mean(stat)) %>%
    deframe()

cDC2_gs <- gene_sets %>%
    filter(program_name == "cDC2") %>%
    pull(genes) %>%
    str_split(",") %>%
    unlist()

plot_fgsea(cDC2_fgsea, dc_mreg_B2M_data, cDC2_gs, "DC mreg", "B2M (2 vs. 0)", "cDC2")
```

## CANCER B2M HEATMAP
```{r message = F, results = F, warning = F}

cancer_counts_filepath <- "/projects/home/tlchan/projects/ascites/second_data_freeze/clusterings/ascites_cancer_R3_300mg_20pm_multi_res/1.3/data/pseudobulk/ascites_cancer_R3_300mg_20pm_1_3_pseudobulk_counts.csv"
cancer_meta_filepath <- "/projects/home/tlchan/projects/ascites/second_data_freeze/clusterings/ascites_cancer_R3_300mg_20pm_multi_res/1.3/data/pseudobulk/ascites_cancer_R3_300mg_20pm_1_3_pseudobulk_meta.csv"

# Normalize counts
counts <- read_csv(cancer_counts_filepath) %>% column_to_rownames("featurekey")
norm_counts <- apply(counts, 2, function(c) {
    n_total <- sum(c)
    per_100k <- (c * 1000000) / n_total
    return(per_100k)
})
norm_counts <- log1p(norm_counts)

sig_genes_filepath <- "/projects/home/tlchan/projects/ascites/ascites_deg_results/cancer/cancer_de_by_B2M_all_results.csv"
sig_genes <- read.csv(sig_genes_filepath) %>%
    filter(padj < 0.05) %>%
    arrange(padj) %>%
    pull(gene_symbol)

# Get mapping
meta <- read.csv(cancer_meta_filepath) %>%
    select(c("patient_id", "B2M")) %>%
    arrange(B2M, patient_id)

# Make and scale heatmap matrix
heatmap_mtx <- norm_counts[sig_genes,]
heatmap_mtx <- t(scale(t(heatmap_mtx)))
heatmap_mtx <- heatmap_mtx[, meta$patient_id]

patients <- colnames(heatmap_mtx)
codes <- paste(lapply(patients, function(patient) meta$B2M[match(patient, meta$patient_id)]), sep = " ", collapse = NULL)

patient_col_fun <- c("#FFFF00", "#1CE6FF", "#FF34FF", "#FF4A46", "#008941", "#006FA6", "#A30059", "#FFDBE5", "#7A4900",
                     "#0000A6", "#63FFAC", "#B79762", "#004D43", "#8FB0FF", "#997D87", "#5A0007", "#809693", "#6A3A4C",
                     "#1B4400", "#4FC601", "#3B5DFF", "#4A3B53", "#FF2F80")
names(patient_col_fun) <- patients

patient_bar <- HeatmapAnnotation(B2M = codes,
                                 col = list(B2M = c('0' = '#fff2ac', '1' = '#fed16e', '2' = '#fd9941')),
                                 show_legend = TRUE,
                                 show_annotation_name = FALSE)

# Function for coloring the heatmap
heatmap_col_fun <- colorRamp2(c(min(heatmap_mtx), 0, max(heatmap_mtx)), c("purple", "black", "yellow"))

# This creates the dendrogram for the samples, using euclidean distance and Ward method. These can def be changed. see documentation
clustering_cols <- hclust(dist(t(heatmap_mtx), method = "euclidean"), method = "ward.D2")
col_hc <- as.dendrogram(clustering_cols)

# This creates the dendrogram for the genes
clustering_rows <- hclust(dist(heatmap_mtx, method = "euclidean"), method = "ward.D2")
row_hc <- as.dendrogram(clustering_rows)

cancer_hmap <- Heatmap(heatmap_mtx,
                       name = "z-score",
                       col = heatmap_col_fun,
                       top_annotation = patient_bar,
                       show_column_names = TRUE,
                       show_row_names = TRUE,
                       column_names_gp = gpar(fontsize = 12),
                       row_names_gp = gpar(cex = 0.5, fontsize = 10),
                       cluster_columns = FALSE,
                       cluster_rows = row_hc,
                       show_heatmap_legend = TRUE,
                       column_title = "Patient",
                       row_title = "Genes")

draw(cancer_hmap)
```