---
title: "Supplemental Figure 7"
output: rmarkdown::github_document
---

## Set up

Load R libraries
```{r message = F, results = F, warning = F, load_r_libraries}
library(ggpubr)
library(glue)
library(openxlsx)
library(tidyverse)

library(reticulate)
use_python("/projects/home/tlchan/.conda/envs/myenv/bin/python")

setwd('/projects/home/tlchan/github_code/ascites/functions')
source('plot_deg.R')
source('plot_dotplot.R')
```

Load python libraries
```{python load_python_packages}
import matplotlib.pyplot as plt
import pegasus as pg

import sys
sys.path.append("/projects/home/tlchan/github_code/ascites/functions")
import python_functions
```

## Supplemental Figure 7D
```{r message = F, results = F, warning = F, fig.width = 12, fig.height = 6, supp_7D}

CFSE_palette <- c("CFSE_pos" = '#fa9f42', "CFSE_neg" = '#6F4E37', 'Other' = '#000000')

excel_file <- glue('/projects/home/tlchan/projects/ascites/results/abundance/mlr_data/combo_mlr_all_lineage_CFSE_abundance.xlsx')

abundance <- read.xlsx(excel_file, sheet = "abundance")
pt_res <- read.xlsx(excel_file, sheet = "CFSEposvCFSEneg_pt")

max_diff <- max(pt_res$Difference)
pt_res$clean_pvals <- sapply(pt_res$p, function(x) {
    if (x > 0.01) {
        return(as.character(round(x, 2)))
    } else if (x < 0.01 & x > 0.001) {
        return(as.character(round(x, 3)))
    } else {
        formatC(x, format = "e", digits = 0)
    }
})

fp <- ggplot(pt_res, aes(x = Difference, y = factor(lineage), color = color, label = clean_pvals)) +
    geom_point(size = 3) +
    geom_text(x = max_diff + 0.05, size = 5, hjust = 0, nudge_y = -0.2) +
    geom_errorbarh(mapping = aes(xmin = CI_low, xmax = CI_high, height = 0)) +
    geom_vline(xintercept = 0) +
    scale_y_discrete(limits = rev) +
    guides(color = "none") +
    xlab("Diff") +
    ylab("Lineage") +
    theme_classic(base_size = 27) +
    scale_color_manual(values = CFSE_palette)

bp <- ggplot(abundance, aes(x = proportion + 1, y = factor(lineage), fill = Channel)) +
    geom_boxplot(outlier.shape = NA) +
    geom_point(pch = 21, position = position_jitterdodge(), aes(fill = Channel), size = 2) +
    scale_x_log10() +
    coord_cartesian(clip = "off") +
    scale_y_discrete(limits = rev) +
    labs(fill = "CFSE") +
    xlab("Percent sample + 1") +
    ylab("") +
    theme_classic(base_size = 27) +
    theme(axis.text.y = element_blank(), axis.text = element_text(size = 20)) +
    scale_fill_manual(values = CFSE_palette)

ggarrange(fp, bp, ncol = 2, nrow = 1, widths = c(0.5, 1.0), common.legend = TRUE, legend = "bottom")

# ggsave("/projects/home/tlchan/fig_panels/supp_7d.pdf", width = 8, height = 8)
```

## Supplemental Figure 7E
```{r message = F, results = F, warning = F, fig.width = 12, fig.height = 6, supp_7E}

DC_palette <- c("cDC1" = '#B8ABE0', "cDC2" = '#7F3F98', "DC: PIGR, RORC" = '#FFC857')

excel_file <- glue('/projects/home/tlchan/projects/ascites/results/abundance/mlr_data/combo_mlr_all_CFSE_neg_lineage_DC_type_abundance.xlsx')

abundance <- read.xlsx(excel_file, sheet = "abundance") %>%
    mutate(DC_type = ifelse(DC_type == "newDC", "DC: PIGR, RORC", DC_type)) %>%
    mutate(DC_type = ifelse(DC_type == "DC1", "cDC1", DC_type)) %>%
    mutate(DC_type = ifelse(DC_type == "DC2", "cDC2", DC_type))

ggplot(data = abundance, aes(y = factor(lineage), x = proportion + 1, fill = DC_type)) +
    geom_boxplot(outlier.shape = NA, alpha = 0.75) +
    geom_jitter(data = abundance, aes(fill = patient_id, group = DC_type), pch = 21, size = 2.75, position = position_jitterdodge(jitter.width = 0.1)) +
    scale_fill_manual(values = DC_palette) +
    labs(fill = "DC Type") +
    scale_x_log10() +
    ylab("Lineages") +
    xlab("Percent sample + 1") +
    theme_classic(base_size = 27) +
    theme(legend.position = "bottom")

# ggsave("/projects/home/tlchan/fig_panels/supp_7e.pdf", width = 8, height = 8)
```

## Supplemental Figure 7F
```{r message = F, results = F, warning = F, fig.width = 12, fig.height = 6, supp_7F}
DC_palette <- c("cDC1" = '#B8ABE0', "cDC2" = '#7F3F98', "DC: PIGR, RORC" = '#FFC857')

excel_file <- glue('/projects/home/tlchan/projects/ascites/results/abundance/mlr_data/combo_mlr_all_CFSE_neg_lineage_DC_type_abundance.xlsx')

abundance <- read.xlsx(excel_file, sheet = "abundance") %>%
    mutate(DC_type = ifelse(DC_type == "newDC", "DC: PIGR, RORC", DC_type)) %>%
    mutate(DC_type = ifelse(DC_type == "DC1", "cDC1", DC_type)) %>%
    mutate(DC_type = ifelse(DC_type == "DC2", "cDC2", DC_type))

# Remap patient IDs
patient_mapping <- read.csv("/projects/home/tlchan/projects/ascites/figure_panels/data/patient_name_remapping.csv")
patient_mapping <- setNames(patient_mapping$new_id, patient_mapping$patient_id)
abundance$patient_id <- patient_mapping[abundance$patient_id]

ggplot(abundance, aes(x = patient_id, y = abundance, fill = DC_type)) +
    geom_bar(stat = "identity") +
    scale_fill_manual(values = DC_palette) +
    labs(fill = "DC Type") +
    xlab("Patient ID") +
    ylab("Cell count") +
    facet_wrap(~lineage) +
    theme_classic(base_size = 20) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position = "none")

# ggsave("/projects/home/tlchan/fig_panels/supp_7f.pdf", width = 4, height = 8)
```

## Supplemental Figure 7G
```{python results = 'hold', supp_7G}
cd8_cluster_palette = {
    "1": "#FF0029",
    "2": "#377EB8",
    "3": "#66A61E",
    "4": "#984EA3",
    "5": "#00D2D5",
    "6": "#FF7F00",
    "7": "#AF8D00"
}

# Load single-cell object
combo_mlr_cd8 = pg.read_input(
    '/projects/home/tlchan/projects/ascites/mlr_data/clusterings/combo_mlr_cd8_R3_500mg_20pm_harm_batch_multi_res/1.3/data/pseudobulk/combo_mlr_cd8_R3_500mg_20pm_harm_batch_1_3_complete_with_pb.zarr.zip')

fig = python_functions.plot_umap(lin_data=combo_mlr_cd8,
                                 color="leiden_labels",
                                 palette=cd8_cluster_palette,
                                 legend_loc=None)

plt.show()
# plt.savefig("/projects/home/tlchan/fig_panels/supp_7g.pdf")
plt.close(fig)
```

## Supplemental Figure 7H,J
```{r message = F, results = F, warning = F, fig.width = 12, fig.height = 6, supp_7HJ}
# Use Reds
reds_colormap <- read.table('/projects/home/tlchan/util/cmaps/reds_cmap.txt', header = FALSE)
reds_hex <- apply(reds_colormap, 1, function(row) {
    rgb(row[1], row[2], row[3], maxColorValue = 1)
})

lineage_list <- list(cd4 = "h", cd8 = "j")

for (lineage in names(lineage_list)) {
    gene_order <- read.xlsx('/projects/home/tlchan/projects/ascites/figure_panels/data/MLR_dotplot_markers.xlsx', sheet = toupper(lineage)) %>%
        filter(!is.na(genes)) %>%
        pull(genes) %>%
        strsplit(",") %>%
        unlist()

    lin_gex <- read.csv(glue('/projects/home/tlchan/projects/ascites/figure_panels/data/dotplot_data/combo_mlr_{lineage}_gene_exp.csv')) %>%
        mutate(Gene = factor(Gene, levels = gene_order), Cluster = factor(Cluster))

    ggplot(lin_gex, aes(x = Gene, y = fct_rev(Cluster), fill = Count, size = Percent_Expressed)) +
        geom_point(color = "black", shape = 21) +
        ylab('Cluster') +
        labs(size = "% Expressed", fill = "Scaled expression") +
        scale_fill_gradientn(colors = reds_hex) +
        lims(size = c(0, 100)) +
        theme_light(base_size = 25) +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, face = "italic")) +
        theme(legend.key.size = unit(.4, "cm"), legend.title = element_text(size = 20), legend.text = element_text(size = 12))
    width <- length(unique(lin_gex$Gene)) / 4 + 7.5
    height <- length(unique(lin_gex$Cluster)) / 2 + 2

    # ggsave(glue("/projects/home/tlchan/fig_panels/supp_7{lineage_list[[lineage]]}.pdf"), width = width, height = height)
}
```

## Supplemental Figure 7I
```{python results = 'hold', supp_7I}
cd4_cluster_palette = {
    "1": "#FF0029",
    "2": "#377EB8",
    "3": "#66A61E",
    "4": "#984EA3",
    "5": "#00D2D5",
    "6": "#FF7F00",
    "7": "#AF8D00",
    "8": "#7F80CD",
    "9": "#B3E900",
}

# Load single-cell object
combo_mlr_cd4 = pg.read_input(
    '/projects/home/tlchan/projects/ascites/mlr_data/clusterings/combo_mlr_cd4_R3_500mg_20pm_harm_batch_multi_res/1.3/data/pseudobulk/combo_mlr_cd4_R3_500mg_20pm_harm_batch_1_3_complete_with_pb.zarr.zip')

fig = python_functions.plot_umap(lin_data=combo_mlr_cd4,
                                 color="leiden_labels",
                                 palette=cd4_cluster_palette,
                                 legend_loc=None)

plt.show()
# plt.savefig("/projects/home/tlchan/fig_panels/supp_7i.pdf")
plt.close(fig)
```

## Supplemental Figure 7K
```{r message = F, results = F, warning = F, fig.width = 12, fig.height = 6, supp_7K}
cfse_neg_res <- read.csv("/projects/home/tlchan/projects/ascites/results/degs/mlr_data/lineage_level/combo_mlr_DC2vDC1_paired/combo_mlr_DC2vDC1_paired_CFSE_neg_de_by_DC2vDC1_paired_all_results.csv")
cfse_pos_res <- read.csv("/projects/home/tlchan/projects/ascites/results/degs/mlr_data/lineage_level/combo_mlr_DC2vDC1_paired/combo_mlr_DC2vDC1_paired_CFSE_pos_de_by_DC2vDC1_paired_all_results.csv")

mlr_meta <- read.csv('/projects/home/tlchan/projects/ascites/results/degs/mlr_data/pb_objects/combo_mlr_lineage_pseudobulk_meta.csv', row.names = 1) %>%
    mutate(DC_type = ifelse(DC_type == "newDC", "DC: PIGR, RORC", DC_type)) %>%
    mutate(DC_type = ifelse(DC_type == "DC1", "cDC1", DC_type)) %>%
    mutate(DC_type = ifelse(DC_type == "DC2", "cDC2", DC_type))

cfse_neg_meta <- mlr_meta %>%
    filter(CFSE == "CFSE_neg") %>%
    filter(DC_type == "cDC1" | DC_type == "cDC2")
cfse_pos_meta <- mlr_meta %>%
    filter(CFSE == "CFSE_pos") %>%
    filter(DC_type == "cDC1" | DC_type == "cDC2")

# pdf("/projects/home/tlchan/fig_panels/supp_7k.pdf", width = 8, height = 8)
plot_lineage_deg(res = cfse_neg_res,
                 meta = cfse_neg_meta,
                 lin = "All CFSE- cells",
                 contrast = "DC_type",
                 ref_var = "cDC1",
                 test_var = "cDC2",
                 ref_color = "#B8ABE0",
                 test_color = "#7F3F98",
                 label_genes = c("CCL4", "IL2", "ISG15", "MYO1F", "AIR1", "TNFSF13B", "CD96", "IL16", "MYC", "RORA"))
plot_lineage_deg(res = cfse_pos_res,
                 meta = cfse_pos_meta,
                 lin = "All CFSE+ cells",
                 contrast = "DC_type",
                 ref_var = "cDC1",
                 test_var = "cDC2",
                 ref_color = "#B8ABE0",
                 test_color = "#7F3F98",
                 label_genes = c("CXCL10", "PDE7B", "MYC", "GBP1", "TNFSF13B", "LAG3", "CD96", "IL16", "CD7", "LAIR1"))
# dev.off()
```