---
title: "Figure 3"
output: rmarkdown::github_document
---

## Set up

Load R libraries
```{r message = F, results = F, warning = F, load_r_libraries}
library(circlize)
library(colorspace)
library(ComplexHeatmap)
library(ggpubr)
library(glue)
library(tidyverse)
library(xlsx)

library(reticulate)
use_python("/projects/home/tlchan/.conda/envs/myenv/bin/python")

setwd('/projects/home/tlchan/github_code/ascites/functions')
source('plot_abundance.R')
source('plot_dotplot.R')
```

Load python libraries
```{python load_python_packages}
import matplotlib.pyplot as plt
import pegasus as pg

import sys
sys.path.append("/projects/home/tlchan/github_code/ascites/functions")
import python_functions
```

## Figure 3A
```{python results = 'hold', fig_3A}
dc_cluster_palette = {
    "1": "#FF0029",
    "2": "#377EB8",
    "3": "#66A61E",
    "4": "#984EA3",
    "5": "#00D2D5",
    "6": "#FF7F00",
    "7": "#AF8D00",
    "8": "#7F80CD",
    "9": "#B3E900",
    "10": "#C42E60"
}

# Load single-cell object
dc_data = pg.read_input(
    '/projects/home/tlchan/projects/ascites/integrated_data/clusterings/ascites_dc_R8_300mg_20pm_harm_channel_multi_res/1.1/data/pseudobulk/ascites_dc_R8_300mg_20pm_harm_channel_1_1_complete_with_pb.zarr.zip')

# Relabel obs for function
dc_data.obs['Cluster'] = dc_data.obs['leiden_labels'].cat.remove_unused_categories().astype(str)

fig = python_functions.plot_umap(lin_data=dc_data,
                                 palette=dc_cluster_palette)

plt.show()
# plt.savefig("/projects/home/tlchan/fig_panels/fig_3a.pdf")
plt.close(fig)
```

## Figure 3B
```{r message = F, results = F, warning = F, fig.width = 8, fig.height = 8, fig_3B}
count_mtx <- read.csv("/projects/home/tlchan/projects/ascites/figure_panels/data/fig_3_data/ascites_dc_R8_300mg_20pm_harm_channel_1_1_cluster_pseudobulk_counts.csv",
                      row.names = 1)
meta_data <- read.csv("/projects/home/tlchan/projects/ascites/figure_panels/data/fig_3_data/ascites_dc_R8_300mg_20pm_harm_channel_1_1_cluster_pseudobulk_meta.csv",
                      row.names = 1)

annot_info <- read.csv("/projects/home/tlchan/projects/ascites/figure_panels/data/fig_3_data/ascites_dc_R8_300mg_20pm_harm_channel_1_1_cluster_pseudobulk_annotation.csv",
                       row.names = 1)

colnames(annot_info) <- sapply(str_replace(colnames(annot_info), "_", " "), str_to_title)
norm_counts <- apply(count_mtx, 2, function(c) {
    n_total <- sum(c)
    per_100k <- (c * 1000000) / n_total
    return(per_100k)
})
norm_counts <- log1p(norm_counts)

all_genes <- apply(annot_info, 2, function(c) {
    genes <- c[0:(nrow(annot_info) - 3)]
    genes <- genes[genes != ""]
    return(genes)
}) %>%
    unlist(use.names = FALSE)
heatmap_data <- norm_counts[unique(all_genes),]
heatmap_data <- scale(t(heatmap_data))
rownames(heatmap_data) <- sapply(rownames(heatmap_data), function(x) paste("Cluster", strsplit(x, "_")[[1]][2]))

clustering <- hclust(dist(heatmap_data, method = "euclidean"), method = "ward.D2")
row_hc <- as.dendrogram(clustering)

order <- clustering$labels[clustering$order]

gene_order <- lapply(order, function(x) {
    genes <- annot_info[[x]][1:(nrow(annot_info) - 3)]
    genes <- genes[genes != ""]
    return(genes)
}) %>%
    unlist(use.names = FALSE)

heatmap_data <- heatmap_data[, gene_order]

label_genes <- list()

# Some custom labelings for interesting genes
label_genes$`Cluster 1` <- c("LILRA4", "IL3RA")
label_genes$`Cluster 2` <- c("IFI6", "CD1D")
label_genes$`Cluster 3` <- c("HLA-DRB1", "HLA-DRA")
label_genes$`Cluster 4` <- c("S100A8", "CSF3R")
label_genes$`Cluster 5` <- c("CLEC9A", "XCR1")
label_genes$`Cluster 6` <- c("SIGLEC6", "KIT")
label_genes$`Cluster 7` <- c("KLF2", "C1QA")
label_genes$`Cluster 8` <- c("NR4A1", "AREG")
label_genes$`Cluster 9` <- c("CCR7", "IL7R")
label_genes$`Cluster 10` <- c("GTF2IRD1", "ACY3", "NRXN2", "HOPX", "PRDM16", "RORC", "SFTPD", "PIGR")

annotation_genes <- unlist(label_genes, use.names = FALSE)

# Now lets organize the color info that will be used for annotations
col_info <- annot_info %>%
    t() %>%
    as.data.frame() %>%
    dplyr::select(-mean_genes) %>%
    rownames_to_column(var = "cluster") %>%
    reshape2::melt(id.vars = c("cluster", "col")) %>%
    select(-variable)

# Get the gene colors
gene_cols <- c()
for (gene in annotation_genes) {
    color <- as.character(filter(col_info, value == gene)["col"][[1]])
    gene_cols <- c(gene_cols, color)
}

bottom_annotation <- HeatmapAnnotation(link = anno_mark(at = match(annotation_genes, colnames(heatmap_data)),
                                                        labels = annotation_genes,
                                                        labels_gp = gpar(col = gene_cols, fontsize = 17, fontface = "italic"),
                                                        side = "bottom"))

mean_genes <- annot_info["mean_genes",] %>%
    mutate_each(funs(as.numeric(as.character(.)))) %>%
    select(rownames(heatmap_data))

gene_col_fun <- colorRamp2(c(min(mean_genes), max(mean_genes)), c("#1d111d", "#bbe7c8"))
gene_bar <- rowAnnotation("mean # genes" = as.numeric(mean_genes),
                          col = list("mean # genes" = gene_col_fun),
                          show_legend = FALSE)
gene_lgd <- Legend(col_fun = gene_col_fun,
                   title = "# genes",
                   direction = "horizontal",
                   title_position = "topcenter",
                   title_gp = gpar(fontsize = 15),
                   labels_gp = gpar(fontsize = 15))

heatmap_col_fun <- colorRamp2(c(min(heatmap_data), 0, max(heatmap_data)), c("purple", "black", "yellow"))
heatmap_lgd <- Legend(col_fun = heatmap_col_fun,
                      title = "z-score",
                      direction = "horizontal",
                      title_position = "topcenter",
                      title_gp = gpar(fontsize = 15),
                      labels_gp = gpar(fontsize = 15))

lgd_list <- packLegend(heatmap_lgd, gene_lgd, column_gap = unit(1, "cm"), direction = "horizontal")

split <- c()
for (gene in colnames(heatmap_data)) {
    for (cl in order) {
        if (gene %in% annot_info[[cl]]) {
            split <- c(split, sub("Cluster", "", cl))
            break
        }
    }
}
split <- factor(split, levels = as.character(unique(split)))

# Make block annotation
column_cols <- c()
for (clust in order) {
    color <- col_info %>%
        select(cluster, col) %>%
        distinct() %>%
        filter(cluster == clust)
    column_cols <- c(column_cols, as.character(color$col))
}

top_annotation <- HeatmapAnnotation(blk = anno_block(gp = gpar(fill = column_cols, col = column_cols)))

clust_cols <- c()
for (clust in rownames(heatmap_data)) {
    color <- col_info %>%
        select(cluster, col) %>%
        distinct() %>%
        filter(cluster == clust)
    clust_cols <- c(clust_cols, as.character(color$col))
}
names(clust_cols) <- rownames(heatmap_data)
right_annotation <- rowAnnotation(clust = names(clust_cols), col = list(clust = clust_cols), show_legend = FALSE)

rownames(heatmap_data) <- sub("Cluster ", "", rownames(heatmap_data))

heatmap_list <- Heatmap(heatmap_data,
                        name = "z-score",
                        col = heatmap_col_fun,
                        cluster_columns = FALSE,
                        cluster_rows = row_hc,
                        clustering_method_rows = "ward.D2",
                        clustering_distance_rows = "euclidean",
                        row_dend_reorder = FALSE,
                        left_annotation = gene_bar,
                        top_annotation = top_annotation,
                        bottom_annotation = bottom_annotation,
                        right_annotation = right_annotation,
                        show_heatmap_legend = FALSE,
                        column_split = split,
                        row_names_side = "right",
                        row_dend_side = "right",
                        column_title_gp = gpar(fontsize = 20),
                        row_names_gp = gpar(fontsize = 20),
                        show_column_names = FALSE)

# pdf("/projects/home/tlchan/fig_panels/fig_3b.pdf", width = 7, height = 8)
draw(heatmap_list, heatmap_legend_list = lgd_list, heatmap_legend_side = "bottom")
# dev.off()
```

## Figure 3C
```{r message = F, results = F, warning = F, fig.width = 14, fig.height = 6, fig_3C}
plot_cluster_abundance(lin = "dc",
                       cluster_order = c(1, 5, 9, 10, 6, 2, 3, 8, 7, 4),
                       n_breaks = 2)

# ggsave("/projects/home/tlchan/fig_panels/fig_3c.pdf", width = 7, height = 8)
```

## Figure 3D
```{r message = F, results = F, warning = F, fig.width = 14, fig.height = 8, fig_3D}
select_regulons <- c("ID2(+)", "IRF4(+)", "IRF7(+)", "IRF8(+)", "KLF5(+)", "TCF4(+)", "SPIB(+)", "NFIL3(+)", "BATF3(+)", "KLF4(+)")

dc10_regulons <- read.xlsx("/projects/home/tlchan/projects/ascites/results/scenic/pigr/test_500_top_regulons.xlsx", sheetName = "dc_10") %>%
    filter(count > 1) %>%
    pull(regulon)
select_regulons <- append(select_regulons, dc10_regulons)

rss_data <- lapply(seq(1, 9, 1), function(i) {
    iter_data <- read.csv(glue("/projects/home/tlchan/projects/ascites/results/scenic/pigr/test_500/lineage_rss_{i}_mtx.csv"), check.names = FALSE, row.names = 1) %>%
        rownames_to_column("cluster") %>%
        pivot_longer(!cluster, names_to = "regulon", values_to = "score") %>%
        mutate(iter = i) %>%
        filter(startsWith(cluster, "dc_"))
    return(iter_data)
}) %>%
    do.call(rbind, .) %>%
    filter(regulon %in% select_regulons)

# Account for regulons that are not found in every cluster
combos <- expand.grid(unique(rss_data$iter), unique(rss_data$cluster), unique(rss_data$regulon)) %>% `colnames<-`(c("iter", "cluster", "regulon"))
rss_data <- combos %>%
    left_join(rss_data, by = c("iter", "cluster", "regulon")) %>%
    replace(is.na(.), 0)

rss_data <- rss_data %>%
    group_by(cluster, regulon) %>%
    summarize(score = mean(score)) %>%
    pivot_wider(names_from = regulon, values_from = score) %>%
    column_to_rownames("cluster") %>%
    t()

# Get Z-scres matrix
rss_data <- t(scale(t(rss_data)))

# Scale to 0 to 1
rss_data <- apply(rss_data, 1, function(r) {
    (r - min(r)) / (max(r) - min(r))
}) %>% t()

# Remove (+) from rownames
rownames(rss_data) <- str_sub(rownames(rss_data), end = -4)

# Function for coloring the heatmap
heatmap_col_fun <- colorRamp2(c(min(rss_data), 0, max(rss_data)), c("purple", "black", "yellow"))

# This creates the dendrogram for the genes
row_order <- c("IRF8", "KLF4", "NFIL3", "MEIS1", "IRF7", "TCF4", "IRF4", "SPIB", "KLF5", "HIC1", "AHR", "RARA", "HOXA6",
               "ELK1", "PDLIM5", "SP7", "HOXA7", "GTF2IRD1", "HOXA9", "DBP", "FOXP2", "BARX1", "NFATC4", "HOXB2",
               "NFIA", "RORC", "ZNF580")

col_order <- c("dc_5", "dc_2", "dc_3", "dc_7", "dc_8", "dc_4", "dc_6", "dc_1", "dc_9", "dc_10")

rss_data <- rss_data[row_order, col_order]

colnames(rss_data) <- c("5", "2", "3", "7", "8", "4", "6", "1", "9", "10")

hmap <- Heatmap(rss_data,
                name = "z-score",
                col = heatmap_col_fun,
                show_column_names = TRUE,
                column_names_rot = 0,
                show_row_names = TRUE,
                cluster_columns = FALSE,
                cluster_rows = FALSE,
                show_heatmap_legend = TRUE,
                column_title = "Cluster",
                row_title = "Regulons",
                row_names_gp = gpar(fontface = "italic")
)

# pdf("/projects/home/tlchan/fig_panels/fig_3d.pdf", width = 4, height = 8)
draw(hmap)
# dev.off()
```

## Figure 3E
```{r message = F, results = F, warning = F, fig.width = 14, fig.height = 8, fig_3E}
corr_mat <- read.csv("/projects/home/tlchan/projects/ascites/results/pearson/integrated_data/human_mouse_pca_corr_matrix_long.csv")

corr_mat <- corr_mat %>% group_by(mouse_cells) %>% mutate(Nor = value/max(value))

corr_mat <- corr_mat %>%
    mutate(human_cells = factor(human_cells, levels = c('1', '6', '10', '9', '8', '7', '4', '3', '2', '5'))) %>%
    mutate(mouse_cells = gsub("_", " ", mouse_cells)) %>%
    mutate(mouse_cells = factor(mouse_cells, levels = c('DC1', 'DC2', 'migratoryDC', 'TC IV', 'Rorc-lo DC', 'TC II', 'TC I', 'TC III', 'tDC', 'pDC')))

ggplot(corr_mat, aes(x = mouse_cells, y = human_cells, fill = Nor)) +
    geom_tile(colour = "black", size = 0.5) +
    xlab("Mouse DC subsets") +
    ylab("Human DC subsets") +
    scale_fill_continuous_diverging(palette = "Blue-Red 3", name ='Normalized Pearson') +
    scale_x_discrete(expand=c(0,0)) +
    scale_y_discrete(expand=c(0,0)) +
    coord_fixed() +
    theme_classic(base_size = 20) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1), legend.position = "bottom") +
    guides(fill = guide_colorbar(title.position = "top", barwidth = 12))

# ggsave("/projects/home/tlchan/fig_panels/fig_3e.pdf", width = 5, height = 5)
```

## Figure 3F
```{r message = F, results = F, warning = F, fig.width = 14, fig.height = 8, fig_3F}
# "Other" organ types
other_organs <- c("Adnexa", "Blood", "Bone marrow", "Liver", "Lung", "Muscle")

# Load data, update values
abundance <- read.csv("/projects/home/tlchan/projects/ascites/figure_panels/data/fig_3_data/external_dcs_obs.csv")

abundance <- abundance %>%
    filter(!dataset %in% c("tonsil")) %>%
    mutate(organ_type = ifelse(organ_type %in% other_organs, "Other", organ_type)) %>%
    group_by(organ, organ_type, dataset, Channel, leiden_labels) %>%
    summarize(n_cell = n())

# Include zeros
combos <- expand.grid(unique(abundance$Channel), unique(abundance$leiden_labels)) %>%
    `colnames<-`(c("Channel", "leiden_labels")) %>%
    left_join(abundance %>%
                  select("Channel", "organ_type", "organ") %>%
                  distinct(), by = c("Channel"))

abundance <- combos %>%
    left_join(abundance, by = c("Channel", "leiden_labels", "organ_type", "dataset", "organ")) %>%
    replace(is.na(.), 0)

abundance <- abundance %>%
    group_by(organ, Channel) %>%
    mutate(channel_count = sum(n_cell),
           percentage = n_cell / channel_count * 100)

organ_levels <- list("Other", "Upper quadrant", "Skeletal muscle", "Lung", "Liver", "Bone marrow", "Blood", "Adnexa",
                     "Thymus", "Thoracic LN", "Spleen", "Mesenteric LN", "Transverse colon", "Sigmoid colon", "Jejunum LP", "Jejunum epithelium", "Ileum", "Doudenum", "Caecum", "Bowel",
                     "Stomach", "Omentum", "Peritoneum", "Peritoneal washing", "Ascites")

tumor_palette <- list("Peritoneum" = "#66A61E", "GI tract" = "#984EA3", "Lymphoid" = "#00D2D5", "Other" = "#FF7F00")

abundance <- abundance %>%
    filter(leiden_labels == 'dc_17') %>%
    mutate(organ = factor(organ, levels = organ_levels),
           dataset = factor(dataset, levels = c('GEA', 'Ovarian_Cancer', 'Healthy tissue')))

ggplot(abundance, aes(y = organ, x = percentage, fill = organ_type)) +
    geom_boxplot(outlier.shape = NA) +
    geom_point(pch = 21, position = position_jitterdodge(), size = 3) +
    labs(fill = "Organ type") +
    scale_x_continuous(expand = expansion(mult = c(0.1, 0.3))) +
    ylab("Tissue") +
    xlab("Percent of sample") +
    facet_grid(dataset ~ ., scales = "free_y", space = 'free') +
    scale_fill_manual(values = tumor_palette) +
    theme_classic(base_size = 15) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

# ggsave("/projects/home/tlchan/fig_panels/fig_3f.pdf", width = 7, height = 8)
```